// fourteenthmodule.js
// Module 14: Version Control & History (65 Lessons)

const module14_git = {
  name: "14. Version Control (65 Lessons)",
  lessons: [
    // --- PHASE 1: CONFIGURATION & INITIALIZATION (1-10) ---
    {
      title: "Set Git Name",
      why: "Tell Git who you are for your commit signatures.",
      text: 'Type <code>git config --global user.name "SysAdmin"</code>',
      objective: "Configure user.name",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("user.name"),
    },
    {
      title: "Set Git Email",
      why: "Attach your email to your signatures.",
      text: 'Type <code>git config --global user.email "admin@gemini.local"</code>',
      objective: "Configure user.email",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("user.email"),
    },
    {
      title: "List Git Config",
      why: "Verify your global settings.",
      text: "Type <code>git config --list</code>",
      objective: "Type git config --list",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("--list"),
    },
    {
      title: "Create Repo Folder",
      why: "Make a folder for our source code.",
      text: "Type <code>mkdir sourcecode</code>",
      objective: "Type mkdir sourcecode",
      xp: 10,
      check: (c, a) => c === "mkdir" && a[0] === "sourcecode",
    },
    {
      title: "Enter Repo Folder",
      why: "Step into the new directory.",
      text: "Type <code>cd sourcecode</code>",
      objective: "Type cd sourcecode",
      xp: 10,
      check: (c, a) => c === "cd" && a[0] === "sourcecode",
    },
    {
      title: "Initialize Repository",
      why: "Turn a normal folder into a Git tracking repository.",
      text: "Type <code>git init</code>",
      objective: "Type git init",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "init",
    },
    {
      title: "Check Repo Status",
      why: "Check the current tracking state.",
      text: "Type <code>git status</code>",
      objective: "Type git status",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "status",
    },
    {
      title: "Create First File",
      why: "Write some initial code.",
      text: 'Type <code>echo "v1.0" > code.txt</code>',
      objective: "Create code.txt",
      xp: 15,
      check: (c, a) =>
        c === "echo" && a.includes(">") && a.includes("code.txt"),
    },
    {
      title: "Stage the File",
      why: "Tell Git to prepare this file to be saved.",
      text: "Type <code>git add code.txt</code>",
      objective: "Type git add code.txt",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "add" && a[1] === "code.txt",
    },
    {
      title: "Verify Staging",
      why: "Check the status to ensure the file is green (staged).",
      text: "Type <code>git status</code>",
      objective: "Type git status",
      xp: 10,
      check: (c, a) => c === "git" && a[0] === "status",
    },

    // --- PHASE 2: COMMITTING & DIFFERENCES (11-20) ---
    {
      title: "First Commit",
      why: "Permanently save the staged snapshot to the timeline.",
      text: 'Type <code>git commit -m "Initial commit"</code>',
      objective: "Type git commit -m",
      xp: 30,
      check: (c, a) => c === "git" && a.includes("commit") && a.includes("-m"),
    },
    {
      title: "Modify Code",
      why: "Make a change to the tracked file.",
      text: 'Type <code>echo "v2.0" >> code.txt</code>',
      objective: "Append to code.txt",
      xp: 15,
      check: (c, a) =>
        c === "echo" && a.includes(">>") && a.includes("code.txt"),
    },
    {
      title: "Check Modified Status",
      why: "Git sees the file changed but isn't staged yet.",
      text: "Type <code>git status</code>",
      objective: "Type git status",
      xp: 10,
      check: (c, a) => c === "git" && a[0] === "status",
    },
    {
      title: "Check Differences",
      why: "See EXACTLY what lines changed in the code.",
      text: "Type <code>git diff</code>",
      objective: "Type git diff",
      xp: 25,
      check: (c, a) =>
        c === "git" && a[0] === "diff" && !a.includes("--staged"),
    },
    {
      title: "Stage All Changes",
      why: "Stage every modified file in the folder at once.",
      text: "Type <code>git add .</code>",
      objective: "Type git add .",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "add" && a[1] === ".",
    },
    {
      title: "Check Staged Diff",
      why: "See the differences of files that are ALREADY staged.",
      text: "Type <code>git diff --staged</code>",
      objective: "Type git diff --staged",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "diff" && a.includes("--staged"),
    },
    {
      title: "Second Commit",
      why: "Save the v2.0 update.",
      text: 'Type <code>git commit -m "Added v2.0"</code>',
      objective: "Type git commit -m",
      xp: 30,
      check: (c, a) => c === "git" && a.includes("commit") && a.includes("-m"),
    },
    {
      title: "Rename Tracked File",
      why: "Safely rename a file without confusing Git.",
      text: "Type <code>git mv code.txt app.txt</code>",
      objective: "Type git mv",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "mv" && a[1] === "code.txt",
    },
    {
      title: "Delete Tracked File",
      why: "Safely delete a file from the repository.",
      text: "Type <code>git rm app.txt</code>",
      objective: "Type git rm",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "rm" && a[1] === "app.txt",
    },
    {
      title: "Commit Destruction",
      why: "Save the deletion state.",
      text: 'Type <code>git commit -m "Removed app"</code>',
      objective: "Commit the deletion",
      xp: 30,
      check: (c, a) => c === "git" && a.includes("commit") && a.includes("-m"),
    },

    // --- PHASE 3: THE TIMELINE & TIME TRAVEL (21-30) ---
    {
      title: "View Git Log",
      why: "See the complete history of commits.",
      text: "Type <code>git log</code>",
      objective: "Type git log",
      xp: 20,
      check: (c, a) =>
        c === "git" && a[0] === "log" && !a.includes("--oneline"),
    },
    {
      title: "Compact Log",
      why: "View the history in a clean, one-line summary.",
      text: "Type <code>git log --oneline</code>",
      objective: "Type git log --oneline",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "log" && a.includes("--oneline"),
    },
    {
      title: "Patch Log",
      why: "View the log AND the exact code diffs of every commit.",
      text: "Type <code>git log -p</code>",
      objective: "Type git log -p",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "log" && a.includes("-p"),
    },
    {
      title: "Graph Log",
      why: "View branching visually in the terminal.",
      text: "Type <code>git log --graph</code>",
      objective: "Type git log --graph",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "log" && a.includes("--graph"),
    },
    {
      title: "Limit Log Output",
      why: "Show only the last 2 commits.",
      text: "Type <code>git log -n 2</code>",
      objective: "Type git log -n 2",
      xp: 20,
      check: (c, a) =>
        c === "git" && a[0] === "log" && a.includes("-n") && a.includes("2"),
    },
    {
      title: "Show Commit",
      why: "Inspect a specific commit by passing its hash.",
      text: "Type <code>git show HEAD</code>",
      objective: "Type git show HEAD",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "show",
    },
    {
      title: "Amend Commit",
      why: "Oh no, you made a typo in the last commit message! Fix it.",
      text: 'Type <code>git commit --amend -m "Fixed message"</code>',
      objective: "Use --amend",
      xp: 35,
      check: (c, a) =>
        c === "git" && a.includes("commit") && a.includes("--amend"),
    },
    {
      title: "Revert Commit",
      why: "Safely undo a commit by creating a reverse commit.",
      text: "Type <code>git revert HEAD</code>",
      objective: "Type git revert HEAD",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "revert" && a[1] === "HEAD",
    },
    {
      title: "Soft Reset",
      why: "Undo the last commit but keep your local file changes.",
      text: "Type <code>git reset --soft HEAD~1</code>",
      objective: "Use git reset --soft",
      xp: 45,
      check: (c, a) => c === "git" && a[0] === "reset" && a.includes("--soft"),
    },
    {
      title: "Hard Reset",
      why: "Nuclear Option: Destroy the last commit AND delete the files.",
      text: "Type <code>git reset --hard HEAD~1</code>",
      objective: "Use git reset --hard",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "reset" && a.includes("--hard"),
    },

    // --- PHASE 4: BRANCHING & MERGING (31-40) ---
    {
      title: "List Branches",
      why: "See all active timelines.",
      text: "Type <code>git branch</code>",
      objective: "Type git branch",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "branch" && a.length === 1,
    },
    {
      title: "Create Branch",
      why: "Spin up an experimental timeline.",
      text: "Type <code>git branch dev</code>",
      objective: "Type git branch dev",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "branch" && a[1] === "dev",
    },
    {
      title: "Checkout Branch",
      why: "Switch into the experimental timeline (Old method).",
      text: "Type <code>git checkout dev</code>",
      objective: "Type git checkout dev",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "checkout" && a[1] === "dev",
    },
    {
      title: "Switch Branch",
      why: "Switch into a timeline (Modern method).",
      text: "Type <code>git switch main</code>",
      objective: "Type git switch main",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "switch" && a[1] === "main",
    },
    {
      title: "Create & Switch",
      why: "Create a branch and jump into it instantly.",
      text: "Type <code>git checkout -b feature</code>",
      objective: "Use git checkout -b",
      xp: 25,
      check: (c, a) =>
        c === "git" &&
        a[0] === "checkout" &&
        a.includes("-b") &&
        a.includes("feature"),
    },
    {
      title: "Create Feature",
      why: "Add code to the feature branch.",
      text: 'Type <code>echo "New Feature" > feat.txt && git add . && git commit -m "Feat"</code>',
      objective: "Commit to feature branch",
      xp: 40,
      check: (c, a, o, raw) =>
        raw.includes("git commit") && raw.includes("Feat"),
    },
    {
      title: "Switch to Main",
      why: "Go back to the production timeline.",
      text: "Type <code>git switch main</code>",
      objective: "Switch to main",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "switch" && a[1] === "main",
    },
    {
      title: "Merge Branch",
      why: "Merge the feature code into production.",
      text: "Type <code>git merge feature</code>",
      objective: "Type git merge feature",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "merge" && a[1] === "feature",
    },
    {
      title: "Delete Branch",
      why: "Clean up the merged branch (-d).",
      text: "Type <code>git branch -d feature</code>",
      objective: "Type git branch -d feature",
      xp: 25,
      check: (c, a) =>
        c === "git" &&
        a[0] === "branch" &&
        a.includes("-d") &&
        a.includes("feature"),
    },
    {
      title: "Force Delete",
      why: "Destroy an unmerged branch (-D).",
      text: "Type <code>git branch -D dev</code>",
      objective: "Type git branch -D dev",
      xp: 25,
      check: (c, a) =>
        c === "git" &&
        a[0] === "branch" &&
        a.includes("-D") &&
        a.includes("dev"),
    },

    // --- PHASE 5: STASHING & REBASING (41-50) ---
    {
      title: "Stage Work",
      why: "Create some messy work.",
      text: "Type <code>touch messy.txt && git add .</code>",
      objective: "Stage a messy file",
      xp: 20,
      check: (c, a, o, raw) => raw.includes("touch") && raw.includes("git add"),
    },
    {
      title: "Stash Changes",
      why: "Hide your messy work in the clipboard temporarily.",
      text: "Type <code>git stash</code>",
      objective: "Type git stash",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "stash" && !a.includes("pop"),
    },
    {
      title: "List Stashes",
      why: "See your clipboard history.",
      text: "Type <code>git stash list</code>",
      objective: "Type git stash list",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "list",
    },
    {
      title: "Pop Stash",
      why: "Bring the hidden code back to your screen.",
      text: "Type <code>git stash pop</code>",
      objective: "Type git stash pop",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "pop",
    },
    {
      title: "Apply Stash",
      why: "Bring the code back but KEEP it in the stash clipboard.",
      text: "Type <code>git stash apply</code>",
      objective: "Type git stash apply",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "apply",
    },
    {
      title: "Drop Stash",
      why: "Delete a specific item from the clipboard.",
      text: "Type <code>git stash drop</code>",
      objective: "Type git stash drop",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "drop",
    },
    {
      title: "Clear Stashes",
      why: "Nuke the entire stash clipboard.",
      text: "Type <code>git stash clear</code>",
      objective: "Type git stash clear",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "clear",
    },
    {
      title: "Rebase Branch",
      why: "Rewrite history to place your branch on top of main.",
      text: "Type <code>git rebase main</code>",
      objective: "Type git rebase main",
      xp: 45,
      check: (c, a) => c === "git" && a[0] === "rebase" && a[1] === "main",
    },
    {
      title: "Interactive Rebase",
      why: "Squash or edit the last 3 commits directly.",
      text: "Type <code>git rebase -i HEAD~3</code>",
      objective: "Use git rebase -i",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "rebase" && a.includes("-i"),
    },
    {
      title: "Cherry Pick",
      why: "Steal one specific commit from another branch by hash.",
      text: "Type <code>git cherry-pick abc1234</code>",
      objective: "Type git cherry-pick",
      xp: 45,
      check: (c, a) => c === "git" && a[0] === "cherry-pick",
    },

    // --- PHASE 6: REMOTE REPOSITORIES (51-60) ---
    {
      title: "Add Remote",
      why: "Link your local folder to a GitHub/GitLab server.",
      text: "Type <code>git remote add origin http://git.local/repo.git</code>",
      objective: "Type git remote add origin",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "remote" && a[1] === "add",
    },
    {
      title: "List Remotes",
      why: "Verify the connection URL (-v).",
      text: "Type <code>git remote -v</code>",
      objective: "Type git remote -v",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "remote" && a.includes("-v"),
    },
    {
      title: "Push to Remote",
      why: "Upload your timeline to the server (-u tracks it).",
      text: "Type <code>git push -u origin main</code>",
      objective: "Type git push -u origin main",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "push" && a.includes("-u"),
    },
    {
      title: "Standard Push",
      why: "Once tracked, simply push.",
      text: "Type <code>git push</code>",
      objective: "Type git push",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "push" && a.length === 1,
    },
    {
      title: "Fetch Changes",
      why: "Download remote changes without merging them yet.",
      text: "Type <code>git fetch</code>",
      objective: "Type git fetch",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "fetch",
    },
    {
      title: "Pull Changes",
      why: "Download AND merge remote changes into your code.",
      text: "Type <code>git pull</code>",
      objective: "Type git pull",
      xp: 35,
      check: (c, a) =>
        c === "git" && a[0] === "pull" && !a.includes("--rebase"),
    },
    {
      title: "Pull with Rebase",
      why: "Pull changes and rebase your local code on top of them.",
      text: "Type <code>git pull --rebase</code>",
      objective: "Type git pull --rebase",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "pull" && a.includes("--rebase"),
    },
    {
      title: "Remove Remote",
      why: "Disconnect from the server.",
      text: "Type <code>git remote rm origin</code>",
      objective: "Type git remote rm",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "remote" && a.includes("rm"),
    },
    {
      title: "Go Home",
      why: "Leave the repository.",
      text: "Type <code>cd ~</code>",
      objective: "Type cd ~",
      xp: 10,
      check: (c, a) => c === "cd" && a[0] === "~",
    },
    {
      title: "Clone Repo",
      why: "Download a full repository from a server.",
      text: "Type <code>git clone http://git.local/new_repo.git</code>",
      objective: "Type git clone",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "clone",
    },

    // --- PHASE 7: ADVANCED GIT NINJA (61-65) ---
    {
      title: "Git Blame",
      why: "Find out exactly WHO wrote a line of code, and WHEN.",
      text: "Type <code>git blame app.txt</code>",
      objective: "Type git blame",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "blame",
    },
    {
      title: "Reflog Recovery",
      why: "The ultimate safety net. Shows every jump and reset you ever made.",
      text: "Type <code>git reflog</code>",
      objective: "Type git reflog",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "reflog",
    },
    {
      title: "Clean Untracked",
      why: "Nuke all untracked garbage files from your directory.",
      text: "Type <code>git clean -fd</code>",
      objective: "Type git clean -fd",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "clean" && a.includes("-fd"),
    },
    {
      title: "Create Tag",
      why: "Mark a commit as a specific release version.",
      text: "Type <code>git tag v1.0.0</code>",
      objective: "Type git tag v1.0.0",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "tag",
    },
    {
      title: "Time Lord",
      why: "Module 14 Complete. You control the timeline.",
      text: 'Type <code>echo "Time Lord Achieved"</code>',
      objective: "Type echo",
      xp: 50,
      check: (c, a) => c === "echo" && a.some((x) => x.includes("Time")),
    },
  ],
};
