// fourteenthmodule.js
// Module 14: Version Control & History (65 Lessons)

const module14_git = {
  name: "14. Version Control (65 Lessons)",
  lessons: [
    // --- PHASE 1: CONFIGURATION & INITIALIZATION (1-10) ---
    {
      title: "Set Git Name",
      why: "Git isn't just backup software; it creates legally-binding cryptographic signatures. You must embed your author identity into the global `~/.gitconfig` file before generating hashes.",
      text: 'Type <code>git config --global user.name "SysAdmin"</code>',
      objective: "Configure user.name",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("user.name"),
    },
    {
      title: "Set Git Email",
      why: "Attach your corporate email. This string is mathematically combined with the timestamp and file data to generate the final SHA-1 commit hash.",
      text: 'Type <code>git config --global user.email "admin@gemini.local"</code>',
      objective: "Configure user.email",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("user.email"),
    },
    {
      title: "List Git Config",
      why: "Verify the configuration parser correctly loaded your identity vectors into memory.",
      text: "Type <code>git config --list</code>",
      objective: "Type git config --list",
      xp: 10,
      check: (c, a) =>
        c === "git" && a.includes("config") && a.includes("--list"),
    },
    {
      title: "Create Repo Folder",
      why: "Establish an isolated workspace node on the filesystem for our Version Control operations.",
      text: "Type <code>mkdir project && cd project</code>",
      objective: "mkdir and cd to project",
      xp: 15,
      check: (c, a, o, raw) => raw.includes("mkdir") && raw.includes("cd"),
    },
    {
      title: "Initialize Repository",
      why: "<b>git init</b> is structural. It generates a hidden `.git` folder containing the core database (objects, refs, and the HEAD pointer). This directory is the actual 'brain' of the repository.",
      text: "Type <code>git init</code>",
      objective: "Type git init",
      xp: 20,
      check: (c) => c === "git" && a[0] === "init",
    },
    {
      title: "Create Code File",
      why: "Generate a raw plaintext file. At this exact moment, Git knows nothing about this file; it is completely 'untracked' by the database.",
      text: 'Type <code>echo "v1" > app.txt</code>',
      objective: "Create app.txt",
      xp: 10,
      check: (c, a, o, raw) => raw.includes("echo") && raw.includes("app.txt"),
    },
    {
      title: "Check Status",
      why: "<b>git status</b> forces Git to scan the Working Directory and compare it against its internal index. It will mathematically flag `app.txt` as untracked.",
      text: "Type <code>git status</code>",
      objective: "Type git status",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "status",
    },
    {
      title: "Stage File",
      why: "<b>git add</b> does NOT save the file. It hashes the file's contents into a cryptographic blob and places it in the 'Staging Area' (the Index), priming it for the next architectural snapshot.",
      text: "Type <code>git add app.txt</code>",
      objective: "Type git add app.txt",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "add" && a[1] === "app.txt",
    },
    {
      title: "Verify Staging",
      why: "Running status again proves that the blob pointer has transitioned from 'Untracked' to 'Changes to be committed'.",
      text: "Type <code>git status</code>",
      objective: "Type git status",
      xp: 10,
      check: (c, a) => c === "git" && a[0] === "status",
    },
    {
      title: "First Commit",
      why: "<b>git commit</b> finalizes the operation. It takes the Staging Area, creates a structural 'Tree' object mapping the filenames to the blobs, and generates a 'Commit' object containing your signature and message.",
      text: 'Type <code>git commit -m "Initial commit"</code>',
      objective: "Type git commit -m",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "commit" && a.includes("-m"),
    },

    // --- PHASE 2: HISTORY, DIFFS & TIME TRAVEL (11-20) ---
    {
      title: "Modify File",
      why: "Alter the code to simulate development progression. This creates a divergence between the Working Directory and the HEAD pointer.",
      text: 'Type <code>echo "v2 update" > app.txt</code>',
      objective: "Modify app.txt",
      xp: 10,
      check: (c, a, o, raw) =>
        raw.includes("echo") && raw.includes("v2 update"),
    },
    {
      title: "Git Diff",
      why: "Before staging, <b>git diff</b> mathematically compares the byte-structure of the working file against the last known state in the index, highlighting exact line additions and deletions.",
      text: "Type <code>git diff</code>",
      objective: "Type git diff",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "diff",
    },
    {
      title: "Stage All Changes",
      why: "Using a period (<b>.</b>) commands Git to recursively scan the entire directory tree and hash every single modified or untracked file into the staging index simultaneously.",
      text: "Type <code>git add .</code>",
      objective: "Type git add .",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "add" && a[1] === ".",
    },
    {
      title: "Second Commit",
      why: "Generate the second node. This new Commit object contains a hidden pointer back to the 'Initial commit', creating the foundational Directed Acyclic Graph (DAG) history.",
      text: 'Type <code>git commit -m "Added v2 features"</code>',
      objective: "Commit the v2 changes",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "commit" && a.includes("-m"),
    },
    {
      title: "View History",
      why: "<b>git log</b> traverses the DAG backward from the HEAD pointer, printing the cryptographic SHA-1 hashes, author data, and timestamps for every architectural node.",
      text: "Type <code>git log</code>",
      objective: "Type git log",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "log",
    },
    {
      title: "One-Line History",
      why: "When analyzing enterprise repos with 50,000 commits, standard log formatting is unreadable. <b>--oneline</b> compresses each commit node to its first 7 hex characters and its title string.",
      text: "Type <code>git log --oneline</code>",
      objective: "Type git log --oneline",
      xp: 20,
      check: (c, a) =>
        c === "git" && a.includes("log") && a.includes("--oneline"),
    },
    {
      title: "Show Commit Details",
      why: "<b>git show</b> takes a specific commit hash and dynamically unpacks its Tree object, displaying the exact byte-diffs that were altered at that specific moment in history.",
      text: "Type <code>git show HEAD</code>",
      objective: "Type git show HEAD",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "show" && a[1] === "HEAD",
    },
    {
      title: "Remove File",
      why: "<b>git rm</b> is a dual-action command. It deletes the file physically from the hard drive, AND automatically records the deletion operation into the staging index.",
      text: "Type <code>git rm app.txt</code>",
      objective: "Type git rm app.txt",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "rm" && a[1] === "app.txt",
    },
    {
      title: "Restore File",
      why: "Wait, mistake! <b>git restore</b> (or checkout) commands Git to query the most recent commit (HEAD) and completely rebuild the deleted file on your disk perfectly.",
      text: "Type <code>git restore app.txt</code>",
      objective: "Type git restore app.txt",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "restore" && a[1] === "app.txt",
    },
    {
      title: "Ignore Files",
      why: "Compilers generate temporary junk files (.log, .o). By creating a <b>.gitignore</b> file, you instruct the Git daemon to permanently blind itself to specific file patterns, keeping the database clean.",
      text: 'Type <code>echo "*.log" > .gitignore</code>',
      objective: "Create .gitignore",
      xp: 25,
      check: (c, a, o, raw) =>
        raw.includes("echo") && raw.includes(".gitignore"),
    },

    // --- PHASE 3: BRANCHING & MERGING (21-40) ---
    {
      title: "List Branches",
      why: "A Branch in Git is NOT a copy of the codebase. It is literally just a lightweight, 40-character text pointer aimed at a specific commit hash. 'main' is simply the default pointer name.",
      text: "Type <code>git branch</code>",
      objective: "Type git branch",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "branch",
    },
    {
      title: "Create Branch",
      why: "By creating 'feature-login', you spawn a second 40-character pointer aimed at the exact same commit node that 'main' is currently aimed at.",
      text: "Type <code>git branch feature-login</code>",
      objective: "Create feature-login branch",
      xp: 20,
      check: (c, a) =>
        c === "git" && a[0] === "branch" && a[1] === "feature-login",
    },
    {
      title: "Switch Branch",
      why: "<b>git switch</b> physically detaches the HEAD pointer from 'main' and attaches it to 'feature-login'. Any new commits generated now will only push the new branch pointer forward.",
      text: "Type <code>git switch feature-login</code>",
      objective: "Switch to feature-login",
      xp: 20,
      check: (c, a) =>
        c === "git" && a[0] === "switch" && a[1] === "feature-login",
    },
    {
      title: "Write Branch Code",
      why: "Alter the code. This divergence will isolate these changes to the feature branch timeline.",
      text: 'Type <code>echo "Login System" >> app.txt</code>',
      objective: "Append text",
      xp: 15,
      check: (c, a, o, raw) => raw.includes("echo") && raw.includes(">>"),
    },
    {
      title: "Commit to Branch",
      why: "This commit node is generated. The 'feature-login' pointer advances to this new node, but the 'main' pointer is left completely behind.",
      text: 'Type <code>git commit -am "Added login"</code>',
      objective: "Use git commit -am",
      xp: 30,
      check: (c, a) => c === "git" && a.includes("commit") && a.includes("-am"),
    },
    {
      title: "Switch to Main",
      why: "Watch the magic. When you switch HEAD back to 'main', Git violently deletes the 'Login System' code from your hard drive, resetting your screen to the exact state 'main' was in.",
      text: "Type <code>git switch main</code>",
      objective: "Switch to main",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "switch" && a[1] === "main",
    },
    {
      title: "Merge Branch",
      why: "<b>git merge</b> executes a Fast-Forward or 3-Way algorithm. It mathematically combines the timeline of 'feature-login' into 'main', physically restoring the login code to your hard drive.",
      text: "Type <code>git merge feature-login</code>",
      objective: "Merge feature-login into main",
      xp: 35,
      check: (c, a) =>
        c === "git" && a[0] === "merge" && a[1] === "feature-login",
    },
    {
      title: "Delete Branch",
      why: "The code is safely integrated. Delete the 'feature-login' text pointer. The underlying commit nodes remain permanently safe inside the DAG history.",
      text: "Type <code>git branch -d feature-login</code>",
      objective: "Delete the feature branch",
      xp: 25,
      check: (c, a) =>
        c === "git" &&
        a[0] === "branch" &&
        a.includes("-d") &&
        a.includes("feature-login"),
    },
    {
      title: "Write Conflicting Code",
      why: "We must simulate a Merge Conflict. Alter line 1 of the app.",
      text: 'Type <code>echo "CONFLICT" > app.txt && git commit -am "Main conflict"</code>',
      objective: "Create a conflict in main",
      xp: 30,
      check: (c, a, o, raw) =>
        raw.includes("CONFLICT") && raw.includes("commit"),
    },
    {
      title: "Checkout Flag Shortcut",
      why: "<b>git checkout -b</b> is the legacy shortcut that simultaneously creates a new branch pointer and instantly moves HEAD to it.",
      text: "Type <code>git checkout -b hotfix</code>",
      objective: "Use git checkout -b",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "checkout" && a.includes("-b"),
    },
    {
      title: "Stash Changes",
      why: "You are halfway through coding a hotfix but your boss needs you to switch branches. <b>git stash</b> takes your dirty working directory, compresses it into an anonymous temporary commit, and restores a clean slate.",
      text: "Type <code>git stash</code>",
      objective: "Type git stash",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "stash",
    },
    {
      title: "List Stashes",
      why: "Query the stash stack to verify your dirty code was successfully cached in memory.",
      text: "Type <code>git stash list</code>",
      objective: "Type git stash list",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "list",
    },
    {
      title: "Pop Stash",
      why: "You are back on the hotfix branch. <b>git stash pop</b> extracts the cached temporary commit, physically restores the dirty code to the screen, and deletes the stash memory block.",
      text: "Type <code>git stash pop</code>",
      objective: "Type git stash pop",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "stash" && a[1] === "pop",
    },
    {
      title: "View Commit Graph",
      why: "The ultimate visualization tool. <b>--graph</b> renders the literal topological connections between commits in ASCII art, proving how branches split and merge over time.",
      text: "Type <code>git log --graph --oneline --all</code>",
      objective: "View git graph",
      xp: 35,
      check: (c, a) => c === "git" && a.includes("--graph"),
    },
    {
      title: "Simulate Fast-Forward",
      why: "When you merge a branch, if 'main' hasn't moved at all, Git performs a 'Fast-Forward', literally just sliding the 'main' text pointer forward to match the feature branch without creating a new node.",
      text: 'Type <code>echo "FF" >> app.txt && git commit -am "Fast Forward"</code>',
      objective: "Commit Fast Forward data",
      xp: 20,
      check: (c, a, o, raw) => raw.includes("commit") && raw.includes("FF"),
    },

    // --- PHASE 4: REMOTE REPOSITORIES (41-50) ---
    {
      title: "Add Remote",
      why: "Git is decentralized. To collaborate, you link your local database to a remote server (like GitHub). <b>git remote add</b> maps a URL to a short alias, universally named 'origin'.",
      text: "Type <code>git remote add origin https://github.com/sim/project.git</code>",
      objective: "Add git remote",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "remote" && a[1] === "add",
    },
    {
      title: "Verify Remote",
      why: "The <b>-v</b> (Verbose) flag proves that the URL was parsed and assigned to both the 'fetch' and 'push' network pathways.",
      text: "Type <code>git remote -v</code>",
      objective: "Type git remote -v",
      xp: 15,
      check: (c, a) => c === "git" && a[0] === "remote" && a[1] === "-v",
    },
    {
      title: "Push Code",
      why: "<b>git push</b> establishes a TLS connection to GitHub. It negotiates exactly which cryptographic blobs the server is missing, and transfers the raw database objects upstream.",
      text: "Type <code>git push -u origin main</code>",
      objective: "Type git push -u origin main",
      xp: 40,
      check: (c, a) =>
        c === "git" &&
        a[0] === "push" &&
        a.includes("origin") &&
        a.includes("main"),
    },
    {
      title: "Fetch Changes",
      why: "<b>git fetch</b> connects to GitHub and downloads new code chunks, BUT it hides them in a remote tracking branch (`origin/main`). It deliberately refuses to touch your local screen.",
      text: "Type <code>git fetch origin</code>",
      objective: "Type git fetch origin",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "fetch",
    },
    {
      title: "Pull Changes",
      why: "<b>git pull</b> is a wrapper command. It secretly runs `git fetch` to download the blobs, and then immediately runs `git merge` to fuse that downloaded code aggressively into your screen.",
      text: "Type <code>git pull origin main</code>",
      objective: "Type git pull origin main",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "pull",
    },
    {
      title: "Clone Repository",
      why: "<b>git clone</b> is the absolute starting point for new devs. It automates `init`, `remote add`, `fetch`, and `checkout` all in one seamless architectural command.",
      text: "Type <code>git clone https://github.com/sim/repo.git</code>",
      objective: "Type git clone",
      xp: 35,
      check: (c, a) => c === "git" && a[0] === "clone",
    },
    {
      title: "Rename Branch",
      why: "Due to historical naming conventions, 'master' is deprecated in favor of 'main'. The <b>-M</b> flag forcibly re-labels the local text pointer.",
      text: "Type <code>git branch -M main</code>",
      objective: "Use git branch -M",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "branch" && a.includes("-M"),
    },
    {
      title: "Remove Remote",
      why: "Sever the network link to the GitHub server. This does not delete any local files or history, it only deletes the URL alias from `.git/config`.",
      text: "Type <code>git remote rm origin</code>",
      objective: "Remove origin",
      xp: 20,
      check: (c, a) => c === "git" && a[0] === "remote" && a[1] === "rm",
    },

    // --- PHASE 5: REBASE, RESET & REFLOG (51-65) ---
    {
      title: "Soft Reset",
      why: "You made a typo in a commit. <b>--soft HEAD~1</b> rewinds the HEAD pointer back 1 node, but leaves the file changes perfectly intact in the Staging Area so you can fix them.",
      text: "Type <code>git reset --soft HEAD~1</code>",
      objective: "Use reset --soft",
      xp: 45,
      check: (c, a) => c === "git" && a[0] === "reset" && a.includes("--soft"),
    },
    {
      title: "Hard Reset",
      why: "The Nuclear Option. <b>--hard HEAD~1</b> rewinds the pointer AND violently destroys all uncommitted code from the hard drive, forcing the screen to identically match the older node.",
      text: "Type <code>git reset --hard HEAD~1</code>",
      objective: "Use reset --hard",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "reset" && a.includes("--hard"),
    },
    {
      title: "Revert Commit",
      why: "If code is already on GitHub, you cannot use Reset. <b>git revert</b> generates a brand-new commit that mathematically subtracts the bytes added by the old commit, preserving public timeline integrity.",
      text: "Type <code>git revert HEAD</code>",
      objective: "Type git revert HEAD",
      xp: 45,
      check: (c, a) => c === "git" && a[0] === "revert" && a[1] === "HEAD",
    },
    {
      title: "Rebase Branch",
      why: "Merge creates chaotic, spider-web history. <b>git rebase</b> physically lifts up your entire feature branch and replays its commits one-by-one on top of the newest main branch, creating a flawless, straight timeline.",
      text: "Type <code>git rebase main</code>",
      objective: "Type git rebase main",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "rebase" && a[1] === "main",
    },
    {
      title: "Interactive Rebase",
      why: "The God Tool. <b>-i</b> opens a text editor showing your last 3 commits. You can seamlessly re-order them, squash them into a single node, or rewrite their messages retroactively.",
      text: "Type <code>git rebase -i HEAD~3</code>",
      objective: "Use rebase -i",
      xp: 55,
      check: (c, a) => c === "git" && a[0] === "rebase" && a.includes("-i"),
    },
    {
      title: "Git Blame",
      why: "Forensic tracing. <b>git blame</b> parses the DAG and annotates every single line of a file with the cryptographic hash and author name of whoever last modified that exact line.",
      text: "Type <code>git blame app.txt</code>",
      objective: "Type git blame",
      xp: 30,
      check: (c, a) => c === "git" && a[0] === "blame",
    },
    {
      title: "Reflog Recovery",
      why: "You did a hard reset and lost 3 days of work. <b>git reflog</b> is the hidden safety net. It records every time the HEAD pointer moved, allowing you to manually teleport back to an 'orphaned' commit hash.",
      text: "Type <code>git reflog</code>",
      objective: "Type git reflog",
      xp: 50,
      check: (c, a) => c === "git" && a[0] === "reflog",
    },
    {
      title: "Clean Untracked",
      why: "Remove untracked junk. <b>-fd</b> violently wipes out any folders (-d) and files (-f) in the working directory that Git does not currently index in its database.",
      text: "Type <code>git clean -fd</code>",
      objective: "Type git clean -fd",
      xp: 40,
      check: (c, a) => c === "git" && a[0] === "clean" && a.includes("-fd"),
    },
    {
      title: "Create Tag",
      why: "A Branch moves. A Tag is frozen. <b>git tag</b> creates an immutable pointer to a specific commit hash, usually denoting a production release version.",
      text: "Type <code>git tag v1.0.0</code>",
      objective: "Type git tag",
      xp: 25,
      check: (c, a) => c === "git" && a[0] === "tag",
    },
    {
      title: "Version Control Master",
      why: "You comprehend Directed Acyclic Graphs, remote object tracking, staging indexes, and non-linear rebasing. You have conquered Git.",
      text: 'Type <code>echo "DevOps Engineer Verified"</code>',
      objective: "Echo final message",
      xp: 100,
      check: (c, a, o, raw) => raw.includes("echo") && raw.includes("Verified"),
    },
  ],
};
