// thirdmodule.js
// Module 3: Text Manipulation (65 Lessons)

const module3_textman = {
  name: "3. Text Manipulation (65 Lessons)",
  lessons: [
    // --- ECHO & STREAM REDIRECTION (1-10) ---
    {
      title: "Standard Output Echo",
      why: "When you type a command, Linux sends the results to a data stream called <b>Standard Output (stdout)</b>, which is wired directly to your screen. The <b>echo</b> command simply takes the text you give it and blasts it straight into that stdout stream.",
      text: 'Type <code>echo "hello"</code>',
      objective: 'Type echo "hello"',
      xp: 10,
      check: (c, a) => c === "echo" && a[0] === "hello",
    },
    {
      title: "Write Stream Redirection",
      why: "You can hijack the stdout stream! The right-angle bracket <b>></b> is the Redirection Operator. It catches the text before it hits your screen and forces it into a file. If the file doesn't exist, Linux creates it. If it does exist, it gets completely overwritten.",
      text: 'Type <code>echo "line1" > a.txt</code>',
      objective: "Create file a.txt via redirection",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("a.txt"),
    },
    {
      title: "Overwrite Verification",
      why: "Let's prove how destructive the single <b>></b> operator is. By using it again, you are telling the kernel to truncate (empty) the file completely before dumping 'line2' into it.",
      text: 'Type <code>echo "line2" > a.txt</code>',
      objective: "Overwrite a.txt with line2",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("a.txt"),
    },
    {
      title: "Append Stream Operator",
      why: "If you want to keep existing data, you must use the Append Operator: <b>>></b> (two brackets). This tells the kernel to seek to the absolute bottom of the text document and safely add your new string as a new line.",
      text: 'Type <code>echo "line3" >> a.txt</code>',
      objective: "Append line3 to a.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("a.txt"),
    },
    {
      title: "Double Append Exercise",
      why: "Let's stack another line down into the text buffer. Building files line-by-line using <code>>></code> is a very common way to write bash scripts automatically from the terminal.",
      text: 'Type <code>echo "line4" >> a.txt</code>',
      objective: "Append line4 to a.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("a.txt"),
    },
    {
      title: "Write Sibling File",
      why: "Establish an independent target data store. We will use this secondary file for comparison later.",
      text: 'Type <code>echo "data1" > b.txt</code>',
      objective: "Create b.txt via redirection",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("b.txt"),
    },
    {
      title: "Append Sibling File",
      why: "Grow your secondary text stream buffer.",
      text: 'Type <code>echo "data2" >> b.txt</code>',
      objective: "Append data2 to b.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("b.txt"),
    },
    {
      title: "Null Redirection",
      why: "You can write empty whitespace strings into files. This is often used by sysadmins to initialize empty tracker files or clear out massive log files without deleting the file node itself.",
      text: 'Type <code>echo "" > empty.txt</code>',
      objective: "Redirect an empty string into empty.txt",
      xp: 15,
      check: (c, a) =>
        c === "echo" && a.includes(">") && a.includes("empty.txt"),
    },
    {
      title: "Write Hidden Log",
      why: "Redirection applies perfectly to hidden dotfiles. Hackers frequently use this technique to silently append their SSH keys into a user's hidden <code>.ssh/authorized_keys</code> file.",
      text: 'Type <code>echo "hidden info" > .hide.txt</code>',
      objective: "Redirect into hidden path .hide.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" && a.includes(">") && a.includes(".hide.txt"),
    },
    {
      title: "Append Hidden Log",
      why: "Append directly to your hidden tracker config without exposing it to standard <code>ls</code> commands.",
      text: 'Type <code>echo "more hidden" >> .hide.txt</code>',
      objective: "Append into hidden path .hide.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" && a.includes(">>") && a.includes(".hide.txt"),
    },

    // --- CONCATENATION & READING SYSTEM FILES (11-20) ---
    {
      title: "Read Stream A",
      why: "The <b>cat</b> (concatenate) command opens a file descriptor, reads the raw bytes, and dumps them directly into your stdout screen stream. Let's see what you actually wrote to your first file.",
      text: "Type <code>cat a.txt</code>",
      objective: "Read content buffer of a.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "a.txt",
    },
    {
      title: "Read Stream B",
      why: "Verify your alternate file store metrics.",
      text: "Type <code>cat b.txt</code>",
      objective: "Read content buffer of b.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "b.txt",
    },
    {
      title: "Read Hidden Stream",
      why: "The <code>cat</code> command does not care if a file is hidden (starts with a dot). If you give it the exact name, it will read it.",
      text: "Type <code>cat .hide.txt</code>",
      objective: "Read content buffer of .hide.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === ".hide.txt",
    },
    {
      title: "Read Local Sandbox Notes",
      why: "Read the pre-existing notes file that was loaded when your sandbox booted up.",
      text: "Type <code>cat notes.txt</code>",
      objective: "Read the workspace notes.txt file",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "notes.txt",
    },
    {
      title: "Read System Users Database",
      why: "In Linux, users aren't managed in a fancy GUI; they are stored in a raw plaintext file called <b>/etc/passwd</b>. Using <code>cat</code> on this absolute path will dump the structural layout of every user profile on the system.",
      text: "Type <code>cat /etc/passwd</code>",
      objective: "Read absolute path file /etc/passwd",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/etc/passwd",
    },
    {
      title: "Read Kernel Logs",
      why: "The system logging daemon records almost everything that happens on the computer (boot metrics, hardware changes) in plain text. Let's dump the raw <b>syslog</b>.",
      text: "Type <code>cat /var/log/syslog</code>",
      objective: "Read absolute path file /var/log/syslog",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/var/log/syslog",
    },
    {
      title: "Read Authentication Records",
      why: "Security events (like people typing wrong passwords in SSH) are routed to a specific log called <b>auth.log</b>. This is the first file Blue Teamers check during an incident.",
      text: "Type <code>cat /var/log/auth.log</code>",
      objective: "Read absolute path file /var/log/auth.log",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Read Nonexistent Target Handler",
      why: "If you try to <code>cat</code> a file that isn't there, Linux outputs text into a different stream called <b>Standard Error (stderr)</b>. This allows scripts to handle errors separately from regular data.",
      text: "Type <code>cat missing.txt</code>",
      objective: "Attempt reading missing.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "missing.txt",
    },
    {
      title: "Read Empty File Stream",
      why: "If you read an empty file, the kernel returns exactly 0 bytes to the stdout stream, resulting in a completely blank return to your prompt.",
      text: "Type <code>cat empty.txt</code>",
      objective: "Read content buffer of empty.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "empty.txt",
    },
    {
      title: "Read Directory Error Check",
      why: "<code>cat</code> is strictly a text-stream reader. It cannot read a directory node because directories are structurally formatted tables, not flat text. Attempting this throws a specific 'Is a directory' error.",
      text: "Type <code>cat projects</code>",
      objective: "Attempt reading directory path 'projects'",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects",
    },

    // --- METRIC WORD COUNT AUDITING (21-35) ---
    {
      title: "Audit File A",
      why: "The <b>wc</b> (Word Count) tool calculates data densities. By default, running it against a file returns three columns: the total Lines, the total Words, and the total Bytes.",
      text: "Type <code>wc a.txt</code>",
      objective: "Run word count auditing on a.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "a.txt",
    },
    {
      title: "Audit File B",
      why: "Calculate metrics on your secondary sibling file.",
      text: "Type <code>wc b.txt</code>",
      objective: "Run word count auditing on b.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "b.txt",
    },
    {
      title: "Audit Workspace Notes",
      why: "Check structural notes text density indices.",
      text: "Type <code>wc notes.txt</code>",
      objective: "Run word count auditing on notes.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "notes.txt",
    },
    {
      title: "Audit Passwd Layout",
      why: "Quickly scan the density of the credentials file. If this file suddenly spikes in byte size, a hacker may have injected hundreds of ghost users into the system.",
      text: "Type <code>wc /etc/passwd</code>",
      objective: "Run word count on /etc/passwd",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/etc/passwd",
    },
    {
      title: "Audit System Diagnostics Log",
      why: "Analyze full payload sizing footprints of kernel logs.",
      text: "Type <code>wc /var/log/syslog</code>",
      objective: "Run word count on /var/log/syslog",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/var/log/syslog",
    },
    {
      title: "Audit Authentication Logs",
      why: "Track raw traffic rows within secure access traces.",
      text: "Type <code>wc /var/log/auth.log</code>",
      objective: "Run word count on /var/log/auth.log",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Line Isolation Mode: File A",
      why: "Usually, you don't care about words or bytes. The <b>-l</b> flag isolates line quantities exclusively. Counting lines is how you count 'items' in Linux (e.g., counting lines in the user file tells you exactly how many users exist).",
      text: "Type <code>wc -l a.txt</code>",
      objective: "Isolate line data values on a.txt via -l",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-l") && a.includes("a.txt"),
    },
    {
      title: "Line Isolation Mode: File B",
      why: "Track total record row quantities in your secondary file efficiently.",
      text: "Type <code>wc -l b.txt</code>",
      objective: "Isolate line data values on b.txt via -l",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-l") && a.includes("b.txt"),
    },
    {
      title: "Line Isolation Mode: Notes",
      why: "Measure total instruction rows loaded.",
      text: "Type <code>wc -l notes.txt</code>",
      objective: "Isolate line data values on notes.txt via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("notes.txt"),
    },
    {
      title: "Line Isolation Mode: Credentials",
      why: "Directly assess how many exact user profiles are allocated on the machine.",
      text: "Type <code>wc -l /etc/passwd</code>",
      objective: "Isolate line data values on /etc/passwd via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("/etc/passwd"),
    },
    {
      title: "Line Isolation Mode: Syslog",
      why: "Count ongoing total incident notifications logged by the system daemon.",
      text: "Type <code>wc -l /var/log/syslog</code>",
      objective: "Isolate line data values on /var/log/syslog via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("/var/log/syslog"),
    },
    {
      title: "Word Isolation Mode: File A",
      why: "The <b>-w</b> flag strictly counts words (text strings separated by whitespaces).",
      text: "Type <code>wc -w a.txt</code>",
      objective: "Isolate word count arrays on a.txt via -w",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-w") && a.includes("a.txt"),
    },
    {
      title: "Word Isolation Mode: Notes",
      why: "Measure total instruction string assets.",
      text: "Type <code>wc -w notes.txt</code>",
      objective: "Isolate word count arrays on notes.txt via -w",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-w") && a.includes("notes.txt"),
    },
    {
      title: "Byte Isolation Mode: File A",
      why: "The <b>-c</b> flag extracts explicit total disk byte properties. Every standard ASCII character takes up exactly 1 byte of hard drive space.",
      text: "Type <code>wc -c a.txt</code>",
      objective: "Isolate total byte metrics on a.txt via -c",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-c") && a.includes("a.txt"),
    },
    {
      title: "Byte Isolation Mode: Notes",
      why: "Assess exact memory scaling costs of workspace assets.",
      text: "Type <code>wc -c notes.txt</code>",
      objective: "Isolate total byte metrics on notes.txt via -c",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-c") && a.includes("notes.txt"),
    },

    // --- UPPER STREAM LIMIT SEPARATION (36-50) ---
    {
      title: "Peek File Boundaries: Notes",
      why: "If a log file is 10 GB, running `cat` will freeze your terminal. The <b>head</b> command slices the upper bounding data set out of the configuration, showing you only the top 10 lines by default.",
      text: "Type <code>head notes.txt</code>",
      objective: "Inspect top elements of notes.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "notes.txt",
    },
    {
      title: "Peek File Boundaries: Credentials",
      why: "Instantly examine configuration schemas at the top of parameters. The top of the passwd file usually shows the `root` and `daemon` accounts.",
      text: "Type <code>head /etc/passwd</code>",
      objective: "Inspect top elements of /etc/passwd",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/etc/passwd",
    },
    {
      title: "Peek File Boundaries: Syslog",
      why: "Read the oldest events in a log. The top of the syslog typically contains the raw kernel hardware initialization steps from when the machine was first booted.",
      text: "Type <code>head /var/log/syslog</code>",
      objective: "Inspect top elements of /var/log/syslog",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/var/log/syslog",
    },
    {
      title: "Peek File Boundaries: Auth Logs",
      why: "Read historical early event records from data streams.",
      text: "Type <code>head /var/log/auth.log</code>",
      objective: "Inspect top elements of /var/log/auth.log",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Peek File Boundaries: File A",
      why: "Audit your own user-defined text structures.",
      text: "Type <code>head a.txt</code>",
      objective: "Inspect top elements of a.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "a.txt",
    },
    {
      title: "Peek File Boundaries: File B",
      why: "Audit your secondary user-defined text structures.",
      text: "Type <code>head b.txt</code>",
      objective: "Inspect top elements of b.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "b.txt",
    },
    {
      title: "Line Gated Head Slicing",
      why: "The <b>-n</b> flag restricts the parsing to an explicit integer row value. You are commanding the system to open the file stream, extract exactly 5 rows, and immediately close the file stream.",
      text: "Type <code>head -n 5 notes.txt</code>",
      objective: "Slice exactly 5 rows off notes.txt via head -n",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-n") && a.includes("5"),
    },
    {
      title: "Line Gated Head Slicing: Passwd",
      why: "Isolate only the top 2 admin setup rows cleanly.",
      text: "Type <code>head -n 2 /etc/passwd</code>",
      objective: "Slice exactly 2 rows off /etc/passwd via head -n",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-n") && a.includes("2"),
    },
    {
      title: "Alternate Integer Flag Routing",
      why: "Because system administrators use `head` so frequently, Linux supports a shorthand syntax. You can drop the 'n' and pass the integer directly behind the hyphen.",
      text: "Type <code>head -5 notes.txt</code>",
      objective: "Slice exactly 5 rows using alternative -5 notation",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-5"),
    },
    {
      title: "Write Stream To Nested Folder",
      why: "You can combine Absolute or Relative paths with text redirection. This routes your text payload directly into a file living inside a sub-directory, without requiring you to <code>cd</code> into it first.",
      text: 'Type <code>echo "nested context" > projects/info.txt</code>',
      objective: "Redirect output to projects/info.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" &&
        a.includes(">") &&
        a.some((x) => x.includes("info.txt")),
    },
    {
      title: "Read Nested Stream",
      why: "Concatenate remote assets within subfolders seamlessly.",
      text: "Type <code>cat projects/info.txt</code>",
      objective: "Read contents of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects/info.txt",
    },
    {
      title: "Audit Nested Metrics",
      why: "Check text metrics inside deeper directory architectures.",
      text: "Type <code>wc projects/info.txt</code>",
      objective: "Run word count on projects/info.txt",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "projects/info.txt",
    },
    {
      title: "Peek Nested Boundaries",
      why: "Head analysis matches directory layers completely.",
      text: "Type <code>head projects/info.txt</code>",
      objective: "Inspect top elements of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "projects/info.txt",
    },
    {
      title: "Append Stream into Nested Folder",
      why: "Build content pools across sub-level storage frameworks remotely.",
      text: 'Type <code>echo "more specs" >> projects/info.txt</code>',
      objective: "Append text properties to projects/info.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" &&
        a.includes(">>") &&
        a.some((x) => x.includes("info.txt")),
    },
    {
      title: "Verify Multi-Row Nested Stream",
      why: "Examine complete changes applied to nested tracking parameters.",
      text: "Type <code>cat projects/info.txt</code>",
      objective: "Read updated properties of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects/info.txt",
    },

    // --- GREP EXPRESSION PATTERN FILTERING (51-65) ---
    {
      title: "Expression Filter: Linux",
      why: "The <b>grep</b> (Global Regular Expression Print) tool is a powerhouse. It reads a file line-by-line, runs an evaluation on each line, and instantly drops any line that does not contain your specified string.",
      text: 'Type <code>grep "Linux" notes.txt</code>',
      objective: "Filter lines matching 'Linux' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Linux") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Terminal",
      why: "Locate configuration keys or commands inside document databases.",
      text: 'Type <code>grep "Terminal" notes.txt</code>',
      objective: "Filter lines matching 'Terminal' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Terminal") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Become",
      why: "Isolate keyword instances dynamically.",
      text: 'Type <code>grep "Become" notes.txt</code>',
      objective: "Filter lines matching 'Become' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Become") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Root",
      why: "Grep is case-sensitive by default. It looks for exact ASCII matches.",
      text: 'Type <code>grep "Root" notes.txt</code>',
      objective: "Filter lines matching 'Root' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Root") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Sysadmin Identity",
      why: "This is how system administrators parse large tables. By filtering the user database for your username, you instantly extract your specific User ID (UID) and Home Directory paths.",
      text: 'Type <code>grep "sysadmin" /etc/passwd</code>',
      objective: "Extract sysadmin entries from /etc/passwd",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("sysadmin") && a.includes("/etc/passwd"),
    },
    {
      title: "Expression Filter: System Root Privilege",
      why: "Verify the core system administrator profile by filtering for the highest-privileged account on the machine.",
      text: 'Type <code>grep "root" /etc/passwd</code>',
      objective: "Extract root entries from /etc/passwd",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("root") && a.includes("/etc/passwd"),
    },
    {
      title: "Expression Filter: Kernel Initialization Trace",
      why: "When diagnosing server crashes, you can use grep to parse thousands of syslog rows to instantly pinpoint where the server initiated its boot sequence.",
      text: 'Type <code>grep "Booting" /var/log/syslog</code>',
      objective: "Extract Booting logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Booting") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: Network Handlers Trace",
      why: "Audit hardware states via pattern indexing. Find exactly when the network card came online.",
      text: 'Type <code>grep "Network" /var/log/syslog</code>',
      objective: "Extract Network logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Network") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: App Failures Trace",
      why: "Track crashed services by isolating specific application names inside the system trace.",
      text: 'Type <code>grep "Nginx" /var/log/syslog</code>',
      objective: "Extract Nginx logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Nginx") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: Forensic Security Breaches",
      why: "This is how Blue Teamers detect brute force attacks. Isolate unauthorized footprint attempts instantly from the audit logs.",
      text: 'Type <code>grep "Failed" /var/log/auth.log</code>',
      objective: "Extract Failed attempts from /var/log/auth.log",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Failed") && a.includes("/var/log/auth.log"),
    },
    {
      title: "Expression Filter: Target Attacks Profile",
      why: "Identify usernames actively targeted by attackers during an intrusion audit.",
      text: 'Type <code>grep "root" /var/log/auth.log</code>',
      objective: "Extract root security traces from /var/log/auth.log",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("root") && a.includes("/var/log/auth.log"),
    },
    {
      title: "Expression Filter: Custom Stream A",
      why: "Search entries across files you generated.",
      text: 'Type <code>grep "line1" a.txt</code>',
      objective: "Filter line1 instances from a.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("line1") && a.includes("a.txt"),
    },
    {
      title: "Expression Filter: Custom Stream B",
      why: "Validate value arrays inside custom data structures.",
      text: 'Type <code>grep "data1" b.txt</code>',
      objective: "Filter data1 instances from b.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("data1") && a.includes("b.txt"),
    },
    {
      title: "Expression Filter: Nested Scrape",
      why: "Scrape directory components recursively without moving your terminal pointer.",
      text: 'Type <code>grep "nested" projects/info.txt</code>',
      objective: "Filter lines from projects/info.txt",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("nested") && a.includes("projects/info.txt"),
    },
    {
      title: "The Ultimate Metric Loop",
      why: "You have mastered parsing text files. Combine your final metric audit to validate your notes configuration.",
      text: "Type <code>wc -l notes.txt</code>",
      objective: "Run final verification row counts on notes.txt",
      xp: 30,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("notes.txt"),
    },
  ],
};
