// thirdmodule.js
// Module 3: Text Manipulation (65 Lessons)

const module3_textman = {
  name: "3. Text Manipulation (65 Lessons)",
  lessons: [
    // --- ECHO & STREAM REDIRECTION (1-10) ---
    {
      title: "Standard Output Echo",
      why: "Print text strings directly to stdout.",
      text: 'Type <code>echo "hello"</code>',
      objective: 'Type echo "hello"',
      xp: 10,
      check: (c, a) => c === "echo" && a[0] === "hello",
    },
    {
      title: "Write Stream Redirection",
      why: "The > operator routes output to create or overwrite a file.",
      text: 'Type <code>echo "line1" > a.txt</code>',
      objective: "Create file a.txt via redirection",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("a.txt"),
    },
    {
      title: "Overwrite Verification",
      why: "Using > again on the same path completely truncates previous data.",
      text: 'Type <code>echo "line2" > a.txt</code>',
      objective: "Overwrite a.txt with line2",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("a.txt"),
    },
    {
      title: "Append Stream Operator",
      why: "The >> operator attaches text strings safely to the bottom of files.",
      text: 'Type <code>echo "line3" >> a.txt</code>',
      objective: "Append line3 to a.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("a.txt"),
    },
    {
      title: "Double Append Exercise",
      why: "Stack another line down into the text buffer.",
      text: 'Type <code>echo "line4" >> a.txt</code>',
      objective: "Append line4 to a.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("a.txt"),
    },
    {
      title: "Write Sibling File",
      why: "Establish an independent target data store.",
      text: 'Type <code>echo "data1" > b.txt</code>',
      objective: "Create b.txt via redirection",
      xp: 15,
      check: (c, a) => c === "echo" && a.includes(">") && a.includes("b.txt"),
    },
    {
      title: "Append Sibling File",
      why: "Grow your secondary text stream buffer.",
      text: 'Type <code>echo "data2" >> b.txt</code>',
      objective: "Append data2 to b.txt",
      xp: 20,
      check: (c, a) => c === "echo" && a.includes(">>") && a.includes("b.txt"),
    },
    {
      title: "Null Redirection",
      why: "Write empty whitespace buffers to initialize empty trackers.",
      text: 'Type <code>echo "" > empty.txt</code>',
      objective: "Redirect an empty string into empty.txt",
      xp: 15,
      check: (c, a) =>
        c === "echo" && a.includes(">") && a.includes("empty.txt"),
    },
    {
      title: "Write Hidden Log",
      why: "Redirection applies perfectly to hidden files.",
      text: 'Type <code>echo "hidden info" > .hide.txt</code>',
      objective: "Redirect into hidden path .hide.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" && a.includes(">") && a.includes(".hide.txt"),
    },
    {
      title: "Append Hidden Log",
      why: "Append directly to your hidden tracker config.",
      text: 'Type <code>echo "more hidden" >> .hide.txt</code>',
      objective: "Append into hidden path .hide.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" && a.includes(">>") && a.includes(".hide.txt"),
    },

    // --- CONCATENATION & READING SYSTEM FILES (11-20) ---
    {
      title: "Read Stream A",
      why: "Output complete raw content pools onto your active stdout.",
      text: "Type <code>cat a.txt</code>",
      objective: "Read content buffer of a.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "a.txt",
    },
    {
      title: "Read Stream B",
      why: "Verify alternate file store metrics.",
      text: "Type <code>cat b.txt</code>",
      objective: "Read content buffer of b.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "b.txt",
    },
    {
      title: "Read Hidden Stream",
      why: "Expose hidden data layers explicitly.",
      text: "Type <code>cat .hide.txt</code>",
      objective: "Read content buffer of .hide.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === ".hide.txt",
    },
    {
      title: "Read Local Sandbox Notes",
      why: "Verify predefined template workspace guidelines.",
      text: "Type <code>cat notes.txt</code>",
      objective: "Read the workspace notes.txt file",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "notes.txt",
    },
    {
      title: "Read System Users Database",
      why: "Inspect structural layout models of /etc/passwd credentials.",
      text: "Type <code>cat /etc/passwd</code>",
      objective: "Read absolute path file /etc/passwd",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/etc/passwd",
    },
    {
      title: "Read Kernel Logs",
      why: "Trace system launch errors and active diagnostic tracks.",
      text: "Type <code>cat /var/log/syslog</code>",
      objective: "Read absolute path file /var/log/syslog",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/var/log/syslog",
    },
    {
      title: "Read Authentication Records",
      why: "Track remote security parameters and failed login metrics.",
      text: "Type <code>cat /var/log/auth.log</code>",
      objective: "Read absolute path file /var/log/auth.log",
      xp: 20,
      check: (c, a) => c === "cat" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Read Nonexistent Target Handler",
      why: "Analyze the bash terminal standard missing file error handling routines.",
      text: "Type <code>cat missing.txt</code>",
      objective: "Attempt reading missing.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "missing.txt",
    },
    {
      title: "Read Empty File Stream",
      why: "Empty streams output null, producing a clean prompt jump.",
      text: "Type <code>cat empty.txt</code>",
      objective: "Read content buffer of empty.txt",
      xp: 10,
      check: (c, a) => c === "cat" && a[0] === "empty.txt",
    },
    {
      title: "Read Directory Error Check",
      why: "Cat can only bind to file data descriptors, not directories.",
      text: "Type <code>cat projects</code>",
      objective: "Attempt reading directory path 'projects'",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects",
    },

    // --- METRIC WORD COUNT AUDITING (21-35) ---
    {
      title: "Audit File A",
      why: "Calculate lines, words, and byte arrays inside file boundaries.",
      text: "Type <code>wc a.txt</code>",
      objective: "Run word count auditing on a.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "a.txt",
    },
    {
      title: "Audit File B",
      why: "Calculate metrics on sibling files.",
      text: "Type <code>wc b.txt</code>",
      objective: "Run word count auditing on b.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "b.txt",
    },
    {
      title: "Audit Workspace Notes",
      why: "Check structural notes text density indices.",
      text: "Type <code>wc notes.txt</code>",
      objective: "Run word count auditing on notes.txt",
      xp: 10,
      check: (c, a) => c === "wc" && a[0] === "notes.txt",
    },
    {
      title: "Audit Passwd Layout",
      why: "Quickly scan data density rows inside credentials.",
      text: "Type <code>wc /etc/passwd</code>",
      objective: "Run word count on /etc/passwd",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/etc/passwd",
    },
    {
      title: "Audit System Diagnostics Log",
      why: "Analyze full payload sizing footprints of kernel logs.",
      text: "Type <code>wc /var/log/syslog</code>",
      objective: "Run word count on /var/log/syslog",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/var/log/syslog",
    },
    {
      title: "Audit Authentication Logs",
      why: "Track raw traffic rows within secure access traces.",
      text: "Type <code>wc /var/log/auth.log</code>",
      objective: "Run word count on /var/log/auth.log",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Line Isolation Mode: File A",
      why: "The -l flag isolates line quantities exclusively, stripping word filters.",
      text: "Type <code>wc -l a.txt</code>",
      objective: "Isolate line data values on a.txt via -l",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-l") && a.includes("a.txt"),
    },
    {
      title: "Line Isolation Mode: File B",
      why: "Track total record row quantities efficiently.",
      text: "Type <code>wc -l b.txt</code>",
      objective: "Isolate line data values on b.txt via -l",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-l") && a.includes("b.txt"),
    },
    {
      title: "Line Isolation Mode: Notes",
      why: "Measure total instruction rows loaded.",
      text: "Type <code>wc -l notes.txt</code>",
      objective: "Isolate line data values on notes.txt via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("notes.txt"),
    },
    {
      title: "Line Isolation Mode: Credentials",
      why: "Directly assess user profiles row allocation balances.",
      text: "Type <code>wc -l /etc/passwd</code>",
      objective: "Isolate line data values on /etc/passwd via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("/etc/passwd"),
    },
    {
      title: "Line Isolation Mode: Syslog",
      why: "Count ongoing total incident notifications logged.",
      text: "Type <code>wc -l /var/log/syslog</code>",
      objective: "Isolate line data values on /var/log/syslog via -l",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("/var/log/syslog"),
    },
    {
      title: "Word Isolation Mode: File A",
      why: "The -w flag isolates text strings separated by whitespaces.",
      text: "Type <code>wc -w a.txt</code>",
      objective: "Isolate word count arrays on a.txt via -w",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-w") && a.includes("a.txt"),
    },
    {
      title: "Word Isolation Mode: Notes",
      why: "Measure total instruction string assets.",
      text: "Type <code>wc -w notes.txt</code>",
      objective: "Isolate word count arrays on notes.txt via -w",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-w") && a.includes("notes.txt"),
    },
    {
      title: "Byte Isolation Mode: File A",
      why: "The -c flag extracts explicit total disk byte load properties.",
      text: "Type <code>wc -c a.txt</code>",
      objective: "Isolate total byte metrics on a.txt via -c",
      xp: 20,
      check: (c, a) => c === "wc" && a.includes("-c") && a.includes("a.txt"),
    },
    {
      title: "Byte Isolation Mode: Notes",
      why: "Assess exact memory scaling costs of workspace assets.",
      text: "Type <code>wc -c notes.txt</code>",
      objective: "Isolate total byte metrics on notes.txt via -c",
      xp: 20,
      check: (c, a) =>
        c === "wc" && a.includes("-c") && a.includes("notes.txt"),
    },

    // --- UPPER STREAM LIMIT SEPARATION (36-50) ---
    {
      title: "Peek File Boundaries: Notes",
      why: "Head slices upper bounding data sets out of configurations.",
      text: "Type <code>head notes.txt</code>",
      objective: "Inspect top elements of notes.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "notes.txt",
    },
    {
      title: "Peek File Boundaries: Credentials",
      why: "Instantly examine configuration schemas at the top of parameters.",
      text: "Type <code>head /etc/passwd</code>",
      objective: "Inspect top elements of /etc/passwd",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/etc/passwd",
    },
    {
      title: "Peek File Boundaries: Syslog",
      why: "Read initial initialization startup records from system headers.",
      text: "Type <code>head /var/log/syslog</code>",
      objective: "Inspect top elements of /var/log/syslog",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/var/log/syslog",
    },
    {
      title: "Peek File Boundaries: Auth Logs",
      why: "Read historical early event records from data streams.",
      text: "Type <code>head /var/log/auth.log</code>",
      objective: "Inspect top elements of /var/log/auth.log",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "/var/log/auth.log",
    },
    {
      title: "Peek File Boundaries: File A",
      why: "Audit user-defined text structures.",
      text: "Type <code>head a.txt</code>",
      objective: "Inspect top elements of a.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "a.txt",
    },
    {
      title: "Peek File Boundaries: File B",
      why: "Audit secondary user-defined text structures.",
      text: "Type <code>head b.txt</code>",
      objective: "Inspect top elements of b.txt",
      xp: 10,
      check: (c, a) => c === "head" && a[0] === "b.txt",
    },
    {
      title: "Line Gated Head Slicing",
      why: "The -n flag restricts parsing to an explicit integer row value.",
      text: "Type <code>head -n 5 notes.txt</code>",
      objective: "Slice exactly 5 rows off notes.txt via head -n",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-n") && a.includes("5"),
    },
    {
      title: "Line Gated Head Slicing: Passwd",
      why: "Isolate top admin setup rows cleanly.",
      text: "Type <code>head -n 2 /etc/passwd</code>",
      objective: "Slice exactly 2 rows off /etc/passwd via head -n",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-n") && a.includes("2"),
    },
    {
      title: "Alternate Integer Flag Routing",
      why: "Shorthand syntax supports passing lines directly behind hyphen metrics.",
      text: "Type <code>head -5 notes.txt</code>",
      objective: "Slice exactly 5 rows using alternative -5 notation",
      xp: 25,
      check: (c, a) => c === "head" && a.includes("-5"),
    },
    {
      title: "Write Stream To Nested Folder",
      why: "Route redirected text payloads into nested sub-directories.",
      text: 'Type <code>echo "nested context" > projects/info.txt</code>',
      objective: "Redirect output to projects/info.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" &&
        a.includes(">") &&
        a.some((x) => x.includes("info.txt")),
    },
    {
      title: "Read Nested Stream",
      why: "Concatenate remote assets within subfolders.",
      text: "Type <code>cat projects/info.txt</code>",
      objective: "Read contents of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects/info.txt",
    },
    {
      title: "Audit Nested Metrics",
      why: "Check text metrics inside directory architectures.",
      text: "Type <code>wc projects/info.txt</code>",
      objective: "Run word count on projects/info.txt",
      xp: 15,
      check: (c, a) => c === "wc" && a[0] === "projects/info.txt",
    },
    {
      title: "Peek Nested Boundaries",
      why: "Head analysis matches directory layers completely.",
      text: "Type <code>head projects/info.txt</code>",
      objective: "Inspect top elements of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "head" && a[0] === "projects/info.txt",
    },
    {
      title: "Append Stream into Nested Folder",
      why: "Build content pools across sub-level storage frameworks.",
      text: 'Type <code>echo "more specs" >> projects/info.txt</code>',
      objective: "Append text properties to projects/info.txt",
      xp: 20,
      check: (c, a) =>
        c === "echo" &&
        a.includes(">>") &&
        a.some((x) => x.includes("info.txt")),
    },
    {
      title: "Verify Multi-Row Nested Stream",
      why: "Examine complete changes applied to nested tracking parameters.",
      text: "Type <code>cat projects/info.txt</code>",
      objective: "Read updated properties of projects/info.txt",
      xp: 15,
      check: (c, a) => c === "cat" && a[0] === "projects/info.txt",
    },

    // --- GREP EXPRESSION PATTERN FILTERING (51-65) ---
    {
      title: "Expression Filter: Linux",
      why: "Grep isolates and prints rows explicitly containing your pattern.",
      text: 'Type <code>grep "Linux" notes.txt</code>',
      objective: "Filter lines matching 'Linux' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Linux") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Terminal",
      why: "Locate configuration keys or commands inside document databases.",
      text: 'Type <code>grep "Terminal" notes.txt</code>',
      objective: "Filter lines matching 'Terminal' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Terminal") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Become",
      why: "Isolate keyword instances dynamically.",
      text: 'Type <code>grep "Become" notes.txt</code>',
      objective: "Filter lines matching 'Become' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Become") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Root",
      why: "Muscle memory configuration tracking extraction.",
      text: 'Type <code>grep "Root" notes.txt</code>',
      objective: "Filter lines matching 'Root' from notes.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("Root") && a.includes("notes.txt"),
    },
    {
      title: "Expression Filter: Sysadmin Identity",
      why: "Locate user parameters within systemic text files.",
      text: 'Type <code>grep "sysadmin" /etc/passwd</code>',
      objective: "Extract sysadmin entries from /etc/passwd",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("sysadmin") && a.includes("/etc/passwd"),
    },
    {
      title: "Expression Filter: System Root Privilege",
      why: "Verify access controls directly within user records.",
      text: 'Type <code>grep "root" /etc/passwd</code>',
      objective: "Extract root entries from /etc/passwd",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("root") && a.includes("/etc/passwd"),
    },
    {
      title: "Expression Filter: Kernel Initialization Trace",
      why: "Pinpoint core boot checkpoints inside diagnostics records.",
      text: 'Type <code>grep "Booting" /var/log/syslog</code>',
      objective: "Extract Booting logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Booting") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: Network Handlers Trace",
      why: "Audit hardware states via pattern indexing constraints.",
      text: 'Type <code>grep "Network" /var/log/syslog</code>',
      objective: "Extract Network logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Network") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: App Failures Trace",
      why: "Track crashed services by isolating system trace values.",
      text: 'Type <code>grep "Nginx" /var/log/syslog</code>',
      objective: "Extract Nginx logs from /var/log/syslog",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Nginx") && a.includes("/var/log/syslog"),
    },
    {
      title: "Expression Filter: Forensic Security Breaches",
      why: "Isolate unauthorized brute-force footprints instantly from audit logs.",
      text: 'Type <code>grep "Failed" /var/log/auth.log</code>',
      objective: "Extract Failed attempts from /var/log/auth.log",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("Failed") && a.includes("/var/log/auth.log"),
    },
    {
      title: "Expression Filter: Target Attacks Profile",
      why: "Identify usernames targeted by attackers during intrusion audits.",
      text: 'Type <code>grep "root" /var/log/auth.log</code>',
      objective: "Extract root security traces from /var/log/auth.log",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("root") && a.includes("/var/log/auth.log"),
    },
    {
      title: "Expression Filter: Custom Stream A",
      why: "Search entries across files you generated.",
      text: 'Type <code>grep "line1" a.txt</code>',
      objective: "Filter line1 instances from a.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("line1") && a.includes("a.txt"),
    },
    {
      title: "Expression Filter: Custom Stream B",
      why: "Validate value arrays inside custom data structures.",
      text: 'Type <code>grep "data1" b.txt</code>',
      objective: "Filter data1 instances from b.txt",
      xp: 20,
      check: (c, a) =>
        c === "grep" && a.includes("data1") && a.includes("b.txt"),
    },
    {
      title: "Expression Filter: Nested Scrape",
      why: "Scrape directory components recursively without moving from your prompt.",
      text: 'Type <code>grep "nested" projects/info.txt</code>',
      objective: "Filter lines from projects/info.txt",
      xp: 25,
      check: (c, a) =>
        c === "grep" && a.includes("nested") && a.includes("projects/info.txt"),
    },
    {
      title: "The Ultimate Metric Loop",
      why: "Consolidate line calculations as a complete textual core sign-off validation metrics check.",
      text: "Type <code>wc -l notes.txt</code>",
      objective: "Run final verification row counts on notes.txt",
      xp: 30,
      check: (c, a) =>
        c === "wc" && a.includes("-l") && a.includes("notes.txt"),
    },
  ],
};
