// twentiethmodule.js
// Module 20: IoT & Firmware Hacking (65 Lessons)

const module20_iot = {
  name: "20. IoT & Firmware (65 Lessons)",
  lessons: [
    // --- PHASE 1: FIRMWARE RECON & EXTRACTION (1-15) ---
    {
      title: "Download Router Firmware",
      why: "Internet of Things (IoT) devices run minimal Linux kernels. Hardware manufacturers usually provide the compiled `.bin` firmware updates on their websites. We download a target binary for reverse engineering.",
      text: "Type <code>wget http://vendor.local/firmware_v1.bin</code>",
      objective: "Download firmware",
      xp: 10,
      check: (c, a) => c === "wget" && a.some((x) => x.includes("firmware")),
    },
    {
      title: "Identify Binary",
      why: "Firmware files have no standard structure. The <b>file</b> command attempts to read the 'magic bytes' at the header of the file to determine if it is raw ARM machine code or a compressed Linux filesystem.",
      text: "Type <code>file firmware_v1.bin</code>",
      objective: "Type file firmware_v1.bin",
      xp: 15,
      check: (c, a) => c === "file" && a.includes("firmware_v1.bin"),
    },
    {
      title: "Check Entropy",
      why: "The <b>ent</b> command calculates the mathematical randomness (entropy) of a file. An entropy score of 7.9 or 8.0 indicates the firmware is highly compressed (like LZMA) or heavily encrypted, which dictates our attack methodology.",
      text: "Type <code>ent firmware_v1.bin</code>",
      objective: "Type ent firmware_v1.bin",
      xp: 20,
      check: (c, a) => c === "ent" && a.includes("firmware_v1.bin"),
    },
    {
      title: "Hex Dump Header",
      why: "If `file` fails, we must manually inspect the file's raw bytes. Using <b>xxd | head</b> allows us to look for known Hexadecimal magic signatures (like 'hsqs' for SquashFS).",
      text: "Type <code>xxd firmware_v1.bin | head -n 10</code>",
      objective: "Hexdump the firmware",
      xp: 25,
      check: (c, a, o, raw) => raw.includes("xxd") && raw.includes("head") && raw.includes("firmware_v1.bin"),
    },
    {
      title: "Strings Analysis",
      why: "The <b>strings</b> command extracts printable ASCII data from the raw binary. IoT developers frequently compile hardcoded backdoor passwords, API keys, or debugging directories directly into the C code.",
      text: "Type <code>strings firmware_v1.bin | grep -i password</code>",
      objective: "Grep strings for password",
      xp: 25,
      check: (c, a, o, raw) => raw.includes("strings") && raw.includes("grep") && raw.includes("password"),
    },
    {
      title: "Binwalk Analysis",
      why: "<b>binwalk</b> is the industry standard for firmware analysis. It scans the raw binary file and matches known structural signatures, identifying where the bootloader (U-Boot), Linux Kernel, and filesystem (SquashFS) are physically located inside the `.bin` file.",
      text: "Type <code>binwalk firmware_v1.bin</code>",
      objective: "Analyze with binwalk",
      xp: 30,
      check: (c, a) => c === "binwalk" && a.includes("firmware_v1.bin"),
    },
    {
      title: "Binwalk Extraction",
      why: "The <b>-e</b> flag forces Binwalk to calculate the internal memory offsets and execute extraction tools automatically, tearing the firmware apart into a physical, browsable Linux directory tree.",
      text: "Type <code>binwalk -e firmware_v1.bin</code>",
      objective: "Extract with binwalk",
      xp: 35,
      check: (c, a) => c === "binwalk" && a.includes("-e") && a.includes("firmware_v1.bin"),
    },
    {
      title: "Navigate Filesystem",
      why: "The extraction generated an `_firmware_v1.bin.extracted` staging folder. Enter it to begin the deep dive into the router's architecture.",
      text: "Type <code>cd _firmware_v1.bin.extracted</code>",
      objective: "cd into extracted folder",
      xp: 15,
      check: (c, a) => c === "cd" && a[0].includes("extracted"),
    },
    {
      title: "List SquashFS",
      why: "SquashFS is a highly compressed, read-only filesystem used universally in routers and webcams. Binwalk successfully identified and carved out the `.squashfs` file.",
      text: "Type <code>ls -l *.squashfs</code>",
      objective: "List squashfs files",
      xp: 15,
      check: (c, a) => c === "ls" && a.some(x=>x.includes("squashfs")),
    },
    {
      title: "Unsquash Filesystem",
      why: "If Binwalk failed to extract the internals of the SquashFS file, we use <b>unsquashfs</b> to manually decompress the LZMA block mapping, outputting a `squashfs-root` folder containing the router's `/etc` and `/bin` directories.",
      text: "Type <code>unsquashfs squashfs-root.squashfs</code>",
      objective: "Run unsquashfs",
      xp: 30,
      check: (c, a) => c === "unsquashfs" && a.some(x=>x.includes("squashfs")),
    },
    {
      title: "Enter Root Filesystem",
      why: "Enter the decompressed filesystem. You are now looking at the exact directory structure (/, /etc, /var) that the IoT device sees when it boots up.",
      text: "Type <code>cd squashfs-root</code>",
      objective: "cd squashfs-root",
      xp: 15,
      check: (c, a) => c === "cd" && a[0] === "squashfs-root",
    },
    {
      title: "Firmwalker Execution",
      why: "<b>Firmwalker</b> is a specialized shell script that automates firmware forensics. It recursively scans the filesystem for hardcoded SSL certificates, SSH keys, `/etc/shadow` hashes, and SQLite database files.",
      text: "Type <code>./firmwalker.sh .</code>",
      objective: "Run firmwalker",
      xp: 40,
      check: (c, a) => c.includes("firmwalker") && a.includes("."),
    },

    // --- PHASE 2: EMULATION & DYNAMIC ANALYSIS (16-30) ---
    {
      title: "Read Architecture",
      why: "To run the router's web server on your laptop, you must know its architecture. <b>readelf -h</b> reveals if the embedded binaries were compiled for ARM, MIPS, or x86 instruction sets.",
      text: "Type <code>readelf -h bin/busybox</code>",
      objective: "Read ELF header of busybox",
      xp: 30,
      check: (c, a) => c === "readelf" && a.includes("-h") && a.includes("bin/busybox"),
    },
    {
      title: "Copy QEMU Binary",
      why: "If the router is ARM, your x86 laptop CPU cannot execute its instructions. <b>QEMU</b> translates CPU instructions on the fly. We copy the statically compiled `qemu-arm-static` binary directly into the router's root filesystem.",
      text: "Type <code>cp /usr/bin/qemu-arm-static ./usr/bin/</code>",
      objective: "Copy qemu-arm-static",
      xp: 30,
      check: (c, a) => c === "cp" && a.some(x=>x.includes("qemu-arm")),
    },
    {
      title: "Chroot Execution",
      why: "The <b>chroot</b> (Change Root) command tricks the target binary into believing that the `squashfs-root` folder is actually the absolute `/` (Root) of the hard drive. Combined with QEMU, we can natively execute the ARM binary.",
      text: "Type <code>sudo chroot . /usr/bin/qemu-arm-static /bin/ls</code>",
      objective: "Execute ls via chroot and QEMU",
      xp: 45,
      check: (c, a) => c === "sudo" && a.includes("chroot") && a.includes("/bin/ls"),
    },
    {
      title: "Emulate Web Server",
      why: "IoT devices usually run minimal web servers like `httpd` or `lighttpd`. By chrooting the daemon, we dynamically boot the router's admin panel locally on our laptop, allowing us to interact with it and hunt for vulnerabilities.",
      text: "Type <code>sudo chroot . /usr/bin/qemu-arm-static /usr/sbin/httpd &</code>",
      objective: "Emulate httpd daemon",
      xp: 50,
      check: (c, a) => c === "sudo" && a.includes("chroot") && a.includes("/usr/sbin/httpd"),
    },
    {
      title: "Curl Emulated Server",
      why: "Verify the QEMU translation is successfully rendering the embedded web application.",
      text: "Type <code>curl http://localhost</code>",
      objective: "Curl localhost",
      xp: 15,
      check: (c, a) => c === "curl" && a.some(x=>x.includes("localhost")),
    },
    {
      title: "NVRAM Faker",
      why: "Emulated IoT processes often crash because they try to read physical EEPROM hardware (NVRAM) that doesn't exist on your laptop. <b>nvram-faker</b> intercepts these kernel calls via `LD_PRELOAD` and feeds the process dummy hardware data to keep it alive.",
      text: 'Type <code>sudo chroot . /usr/bin/qemu-arm-static -E LD_PRELOAD=/lib/libnvram-faker.so /usr/sbin/httpd &</code>',
      objective: "Run httpd with nvram-faker",
      xp: 55,
      check: (c, a, o, raw) => raw.includes("chroot") && raw.includes("LD_PRELOAD") && raw.includes("nvram"),
    },
    {
      title: "Dynamic Strace",
      why: "To find zero-days, we attach <b>strace</b> to the emulated process. If we send a malformed web request, strace logs exactly how the ARM binary's memory registers respond, exposing potential Buffer Overflows.",
      text: "Type <code>sudo chroot . /usr/bin/qemu-arm-static -strace /usr/sbin/httpd</code>",
      objective: "Run httpd with qemu strace",
      xp: 55,
      check: (c, a) => c === "sudo" && a.includes("chroot") && a.includes("-strace"),
    },

    // --- PHASE 3: IOT PROTOCOLS (MQTT & COAP) (31-45) ---
    {
      title: "Nmap MQTT",
      why: "IoT devices (smart bulbs, thermostats) communicate using MQTT (Message Queuing Telemetry Transport), a lightweight publish/subscribe protocol operating on TCP port 1883. We scan the network for IoT brokers.",
      text: "Type <code>nmap -p 1883 10.0.0.150</code>",
      objective: "Scan for MQTT",
      xp: 25,
      check: (c, a) => c === "nmap" && a.includes("-p") && a.includes("1883"),
    },
    {
      title: "Mosquitto Subscribe",
      why: "The `mosquitto_sub` client connects to the IoT broker. Using the `#` wildcard subscribes you to ALL topics simultaneously, allowing you to intercept every single plaintext metric (temperature, coordinates) the IoT network broadcasts.",
      text: "Type <code>mosquitto_sub -h 10.0.0.150 -t \"#\" -v &</code>",
      objective: "Subscribe to all MQTT topics",
      xp: 40,
      check: (c, a) => c === "mosquitto_sub" && a.includes("-h") && a.includes("-t") && a.includes('\"#\"'),
    },
    {
      title: "Mosquitto Publish",
      why: "Hackers don't just listen; they control. `mosquitto_pub` injects an unauthorized message into the broker. Publishing 'OFF' to the `/home/door/lock` topic mathematically commands the physical hardware to disengage.",
      text: "Type <code>mosquitto_pub -h 10.0.0.150 -t \"/home/door/lock\" -m \"OFF\"</code>",
      objective: "Publish malicious MQTT message",
      xp: 40,
      check: (c, a) => c === "mosquitto_pub" && a.includes("-t") && a.includes("-m"),
    },
    {
      title: "Nmap CoAP",
      why: "Constrained Application Protocol (CoAP) is an alternative to MQTT that operates over connectionless UDP port 5683. It is highly susceptible to UDP Amplification DDoS attacks.",
      text: "Type <code>nmap -sU -p 5683 10.0.0.150</code>",
      objective: "Scan for CoAP",
      xp: 30,
      check: (c, a) => c === "nmap" && a.includes("-sU") && a.includes("5683"),
    },
    {
      title: "UPnP Discovery",
      why: "Universal Plug and Play (UPnP) runs on port 1900. Nmap can broadcast an M-SEARCH packet to force all smart TVs, routers, and cameras on the network to instantly reply with their exact hardware models and firmware versions.",
      text: "Type <code>nmap -sU -p 1900 --script=upnp-info 10.0.0.0/24</code>",
      objective: "Nmap UPnP script",
      xp: 45,
      check: (c, a) => c === "nmap" && a.includes("--script=upnp-info"),
    },

    // --- PHASE 4: HARDWARE INTERFACES & REPACKING (46-60) ---
    {
      title: "Identify UART Pinout",
      why: "If a router's SSH is locked, researchers crack open the physical plastic case. They look for 4 metal pins on the motherboard: VCC, GND, TX, and RX. This is the Universal Asynchronous Receiver-Transmitter (UART) hardware console.",
      text: 'Type <code>echo "UART Debug Header Located"</code>',
      objective: "Simulate finding UART",
      xp: 15,
      check: (c, a, o, raw) => raw.includes("echo") && raw.includes("UART"),
    },
    {
      title: "Connect Minicom",
      why: "Once TX and RX wires are connected to a USB adapter, <b>minicom</b> establishes a direct serial connection to the motherboard at a baud rate of 115200. This physically bypasses all network firewalls.",
      text: "Type <code>minicom -b 115200 -D /dev/ttyUSB0</code>",
      objective: "Start minicom session",
      xp: 40,
      check: (c, a) => c === "minicom" && a.includes("-b") && a.includes("-D"),
    },
    {
      title: "U-Boot Environment",
      why: "Upon hardware boot, the U-Boot bootloader runs before Linux. By hitting a key quickly, you interrupt the boot sequence. The <b>printenv</b> command dumps the critical hardware memory initialization variables (like `bootargs`).",
      text: "Type <code>printenv</code>",
      objective: "Simulate U-Boot printenv",
      xp: 20,
      check: (c) => c === "printenv",
    },
    {
      title: "Inject init=/bin/sh",
      why: "We manipulate the bootloader variables. Appending `init=/bin/sh` to the kernel arguments bypasses the login sequence completely. When the kernel loads, it drops us instantly into a root shell without asking for a password.",
      text: 'Type <code>setenv bootargs "console=ttyS0,115200 root=/dev/mtdblock2 init=/bin/sh"</code>',
      objective: "Simulate U-Boot setenv",
      xp: 45,
      check: (c, a, o, raw) => raw.includes("setenv") && raw.includes("init=/bin/sh"),
    },
    {
      title: "Dump SPI Flash",
      why: "If UART is disabled, researchers attach a physical hardware clip directly to the EEPROM/SPI flash memory chip on the motherboard. <b>flashrom</b> mathematically reads the chip's raw electrical states and dumps the entire firmware block to disk.",
      text: "Type <code>flashrom -p ch341a_spi -r dumped_flash.bin</code>",
      objective: "Simulate SPI flashrom dump",
      xp: 50,
      check: (c, a) => c === "flashrom" && a.includes("-r") && a.includes("dumped_flash.bin"),
    },
    {
      title: "Compile Cross-Architecture",
      why: "To inject a custom backdoor, you must compile your C code to mathematically match the router's processor. We use an ARM-specific GCC toolchain to cross-compile our payload.",
      text: "Type <code>arm-linux-gnueabihf-gcc backdoor.c -o backdoor_arm</code>",
      objective: "Cross-compile for ARM",
      xp: 45,
      check: (c, a, o, raw) => raw.includes("gcc") && raw.includes("backdoor_arm"),
    },
    {
      title: "Inject Backdoor",
      why: "Move the cross-compiled payload into the extracted filesystem's `/etc/init.d/` directory so the router is forced to run it automatically on boot.",
      text: "Type <code>cp backdoor_arm squashfs-root/etc/init.d/</code>",
      objective: "Move backdoor to init.d",
      xp: 30,
      check: (c, a) => c === "cp" && a.some(x=>x.includes("init.d")),
    },
    {
      title: "Repack SquashFS",
      why: "The filesystem is modified. We use <b>mksquashfs</b> to symmetrically re-compress the directory structure back into a dense LZMA `.squashfs` binary block, preserving inode ownership and block padding.",
      text: "Type <code>mksquashfs squashfs-root modified.squashfs -comp lzma</code>",
      objective: "Run mksquashfs",
      xp: 50,
      check: (c, a) => c === "mksquashfs" && a.includes("-comp") && a.includes("lzma"),
    },
    {
      title: "Stitch Firmware",
      why: "Finally, the <b>dd</b> (Disk Destroyer) command is used to binary-splice the newly compressed filesystem block directly back into the original firmware file, aligning the hex bytes perfectly with the U-Boot header.",
      text: "Type <code>dd if=modified.squashfs of=firmware_v1.bin seek=1024 bs=1K conv=notrunc</code>",
      objective: "Use dd to stitch firmware",
      xp: 60,
      check: (c, a) => c === "dd" && a.includes("seek=1024") && a.includes("conv=notrunc"),
    },
    
    // --- PHASE 5: CLEANUP & CONCLUSION (61-65) ---
    {
      title: "Clean Up Extraction",
      why: "Eradicate the staging directories and modified binary files to secure the workspace.",
      text: "Type <code>rm -rf _firmware* squashfs-root modified.squashfs</code>",
      objective: "Remove firmware folders",
      xp: 20,
      check: (c, a) => c === "rm" && a.includes("-rf") && a.some((x) => x.includes("squashfs-root")),
    },
    {
      title: "Stop MQTT",
      why: "Terminate the background Mosquitto subscription daemons listening to the IoT traffic.",
      text: "Type <code>killall mosquitto_sub</code>",
      objective: "Killall mosquitto_sub",
      xp: 15,
      check: (c, a) => c === "killall" && a.includes("mosquitto_sub"),
    },
    {
      title: "Kill QEMU",
      why: "Terminate the cross-architecture emulator processes and free the allocated RAM.",
      text: "Type <code>killall qemu-arm-static</code>",
      objective: "Killall qemu",
      xp: 15,
      check: (c, a) => c === "killall" && a.includes("qemu-arm-static"),
    },
    {
      title: "Check System Integrity",
      why: "When handling malware and emulating unknown firmwares, always run <b>debsums -c</b> to mathematically verify that none of your own core operating system packages were compromised or corrupted during execution.",
      text: "Type <code>debsums -c</code>",
      objective: "Type debsums -c",
      xp: 30,
      check: (c, a) => c === "debsums" && a.includes("-c"),
    },
    {
      title: "Hardware Master",
      why: "You understand EEPROM logic, UART serial arrays, Cross-Architecture Emulation, and Firmware Re-packing. You are a Hardware Reverse Engineer.",
      text: 'Type <code>echo "Silicon Conquered"</code>',
      objective: "Echo final message",
      xp: 100,
      check: (c, a, o, raw) => raw.includes("echo") && raw.includes("Silicon"),
    },
  ],
};